import mongoose, { Schema, model } from 'mongoose';

const base = { tenantId: { type: Schema.Types.ObjectId, required: true, index: true }, createdAt: { type: Date, default: Date.now }, updatedAt: { type: Date, default: Date.now } };

export const Permission = model('Permission', new Schema({ key: { type: String, unique: true, required: true }, resource: String, action: String, scopeType: String, description: String, status: { type: String, default: 'active' } }, { timestamps: true }));
export const Role = model('Role', new Schema({ ...base, name: { type: String, required: true }, key: { type: String, required: true }, permissionIds: [{ type: Schema.Types.ObjectId, ref: 'Permission' }], scopeRules: Schema.Types.Mixed, isSystemRole: Boolean, status: { type: String, default: 'active' } }, { timestamps: true }));
export const User = model('User', new Schema({ ...base, email: { type: String, required: true }, normalizedEmail: { type: String, required: true }, passwordHash: String, authProvider: { type: String, default: 'local' }, authVersion: { type: Number, default: 1 }, profile: Schema.Types.Mixed, organization: Schema.Types.Mixed, roleIds: [{ type: Schema.Types.ObjectId, ref: 'Role' }], status: { type: String, enum: ['invited', 'active', 'suspended', 'deactivated'], default: 'active' }, lastLoginAt: Date }, { timestamps: true }));
User.schema.index({ tenantId: 1, normalizedEmail: 1 }, { unique: true });
export const AuditLog = model('AuditLog', new Schema({ ...base, actorId: Schema.Types.Mixed, action: { type: String, required: true }, entity: { type: Schema.Types.Mixed, required: true }, oldValue: Schema.Types.Mixed, newValue: Schema.Types.Mixed, timestamp: { type: Date, default: Date.now }, requestId: String, sessionId: String, ip: String, userAgent: String, result: String, metadata: Schema.Types.Mixed }, { timestamps: false, versionKey: false }));
AuditLog.schema.index({ tenantId: 1, 'entity.type': 1, 'entity.id': 1, timestamp: -1 });
export const Contract = model('Contract', new Schema({ ...base, contractNumber: { type: String, required: true }, title: { type: String, required: true }, contractType: { type: String, required: true }, parties: [Schema.Types.Mixed], ownerId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, departmentId: Schema.Types.ObjectId, businessUnitId: Schema.Types.ObjectId, status: { type: String, enum: ['draft', 'review', 'approval', 'signature', 'active', 'monitoring', 'renewal', 'archived'], default: 'draft' }, effectiveDate: Date, expiryDate: Date, renewal: Schema.Types.Mixed, financial: Schema.Types.Mixed, currentVersionId: Schema.Types.ObjectId, risk: Schema.Types.Mixed, tags: [String], metadata: Schema.Types.Mixed, version: { type: Number, default: 1 } }, { timestamps: true }));
Contract.schema.index({ tenantId: 1, contractNumber: 1 }, { unique: true });
Contract.schema.index({ tenantId: 1, status: 1, expiryDate: 1 });
Contract.schema.index({ tenantId: 1, ownerId: 1, status: 1 });
export const ContractVersion = model('ContractVersion', new Schema({ ...base, contractId: { type: Schema.Types.ObjectId, ref: 'Contract', required: true }, versionNumber: { type: Number, required: true }, state: String, changeSummary: String, authorId: Schema.Types.ObjectId, previousVersionId: Schema.Types.ObjectId, contentRef: Schema.Types.Mixed, clauseRefs: [Schema.Types.ObjectId] }, { timestamps: true }));
ContractVersion.schema.index({ contractId: 1, versionNumber: 1 }, { unique: true });

export const Template = model('Template', new Schema({ ...base, name: { type: String, required: true }, key: { type: String, required: true }, contractType: { type: String, required: true }, description: String, status: { type: String, enum: ['draft', 'published', 'retired'], default: 'draft' }, currentVersion: { type: Number, default: 1 }, clauseRefs: [Schema.Types.ObjectId], variables: [Schema.Types.Mixed], ownerId: Schema.Types.ObjectId }, { timestamps: true }));
Template.schema.index({ tenantId: 1, key: 1 }, { unique: true });
Template.schema.index({ tenantId: 1, contractType: 1, status: 1 });
export const TemplateVersion = model('TemplateVersion', new Schema({ ...base, templateId: { type: Schema.Types.ObjectId, ref: 'Template', required: true }, versionNumber: { type: Number, required: true }, status: { type: String, enum: ['draft', 'published', 'retired'], default: 'draft' }, clauseRefs: [Schema.Types.ObjectId], variables: [Schema.Types.Mixed], contentRef: Schema.Types.Mixed, authorId: Schema.Types.ObjectId, publishedAt: Date }, { timestamps: true }));
TemplateVersion.schema.index({ templateId: 1, versionNumber: 1 }, { unique: true });
export const Clause = model('Clause', new Schema({ ...base, key: { type: String, required: true }, title: { type: String, required: true }, body: { type: String, required: true }, category: String, riskClassification: { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'medium' }, tags: [String], status: { type: String, enum: ['draft', 'approved', 'deprecated'], default: 'draft' }, versionNumber: { type: Number, default: 1 }, ownerId: Schema.Types.ObjectId, approvedBy: Schema.Types.ObjectId }, { timestamps: true }));
Clause.schema.index({ tenantId: 1, key: 1 }, { unique: true });
Clause.schema.index({ tenantId: 1, category: 1, riskClassification: 1, status: 1 });
export const ClauseVersion = model('ClauseVersion', new Schema({ ...base, clauseId: { type: Schema.Types.ObjectId, ref: 'Clause', required: true }, versionNumber: { type: Number, required: true }, body: String, status: String, authorId: Schema.Types.ObjectId, approvedBy: Schema.Types.ObjectId, publishedAt: Date }, { timestamps: true }));
ClauseVersion.schema.index({ clauseId: 1, versionNumber: 1 }, { unique: true });
export const Workflow = model('Workflow', new Schema({ ...base, name: { type: String, required: true }, key: { type: String, required: true }, contractType: String, status: { type: String, enum: ['draft', 'published', 'retired'], default: 'draft' }, currentVersion: { type: Number, default: 1 }, triggerRules: [Schema.Types.Mixed], stages: [Schema.Types.Mixed], rejectionPolicy: Schema.Types.Mixed, ownerId: Schema.Types.ObjectId }, { timestamps: true }));
Workflow.schema.index({ tenantId: 1, key: 1 }, { unique: true });
export const WorkflowVersion = model('WorkflowVersion', new Schema({ ...base, workflowId: { type: Schema.Types.ObjectId, ref: 'Workflow', required: true }, versionNumber: { type: Number, required: true }, status: String, triggerRules: [Schema.Types.Mixed], stages: [Schema.Types.Mixed], rejectionPolicy: Schema.Types.Mixed, authorId: Schema.Types.ObjectId, publishedAt: Date }, { timestamps: true }));
WorkflowVersion.schema.index({ workflowId: 1, versionNumber: 1 }, { unique: true });
export const ApprovalTask = model('ApprovalTask', new Schema({ ...base, contractId: { type: Schema.Types.ObjectId, ref: 'Contract', required: true }, workflowId: Schema.Types.ObjectId, workflowVersionId: Schema.Types.ObjectId, stageKey: String, assignedUserId: Schema.Types.ObjectId, assignedRoleId: Schema.Types.ObjectId, status: { type: String, enum: ['pending', 'in_progress', 'approved', 'rejected', 'delegated', 'expired', 'cancelled'], default: 'pending' }, decision: Schema.Types.Mixed, comments: String, dueAt: Date, completedAt: Date, escalation: Schema.Types.Mixed, delegation: Schema.Types.Mixed, history: [Schema.Types.Mixed], version: { type: Number, default: 1 } }, { timestamps: true }));
ApprovalTask.schema.index({ tenantId: 1, assignedUserId: 1, status: 1, dueAt: 1 });
ApprovalTask.schema.index({ tenantId: 1, contractId: 1, status: 1 });

export const SignatureRequest = model('SignatureRequest', new Schema({ ...base, contractId: { type: Schema.Types.ObjectId, ref: 'Contract', required: true }, contractVersionId: Schema.Types.ObjectId, provider: { type: String, required: true }, status: { type: String, enum: ['requested', 'in_progress', 'completed', 'declined', 'expired', 'cancelled'], default: 'requested' }, signers: [Schema.Types.Mixed], expiresAt: Date, createdBy: Schema.Types.ObjectId, completedAt: Date, evidenceRefs: [Schema.Types.Mixed], auditMetadata: Schema.Types.Mixed }, { timestamps: true }));
SignatureRequest.schema.index({ tenantId: 1, contractId: 1, status: 1 });
export const SignatureParticipant = model('SignatureParticipant', new Schema({ ...base, signatureRequestId: { type: Schema.Types.ObjectId, ref: 'SignatureRequest', required: true }, userId: Schema.Types.ObjectId, vendorIdentity: Schema.Types.Mixed, signingOrder: { type: Number, required: true }, status: { type: String, enum: ['pending', 'signed', 'declined'], default: 'pending' }, signedAt: Date, declineReason: String, evidenceRefs: [Schema.Types.Mixed] }, { timestamps: true }));
SignatureParticipant.schema.index({ tenantId: 1, signatureRequestId: 1, signingOrder: 1 });
export const Obligation = model('Obligation', new Schema({ ...base, contractId: { type: Schema.Types.ObjectId, ref: 'Contract', required: true }, ownerId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, type: { type: String, required: true }, title: { type: String, required: true }, description: String, priority: { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'medium' }, dueDate: { type: Date, required: true }, recurrence: Schema.Types.Mixed, status: { type: String, enum: ['open', 'in_progress', 'completed', 'overdue', 'cancelled'], default: 'open' }, escalationPolicy: Schema.Types.Mixed, completionData: Schema.Types.Mixed, evidenceDocuments: [Schema.Types.Mixed], version: { type: Number, default: 1 } }, { timestamps: true }));
Obligation.schema.index({ tenantId: 1, dueDate: 1, status: 1 });
Obligation.schema.index({ tenantId: 1, ownerId: 1, status: 1 });
Obligation.schema.index({ tenantId: 1, contractId: 1, status: 1 });

export const Document = model('Document', new Schema({ ...base, contractId: { type: Schema.Types.ObjectId, ref: 'Contract', required: true }, contractVersionId: Schema.Types.ObjectId, obligationId: Schema.Types.ObjectId, documentType: { type: String, required: true }, fileName: { type: String, required: true }, originalFileName: { type: String, required: true }, mimeType: { type: String, required: true }, sizeBytes: { type: Number, required: true }, checksum: { type: String, required: true }, classification: { type: String, enum: ['public', 'internal', 'confidential', 'restricted'], default: 'confidential' }, storageProvider: { type: String, required: true }, storageKey: { type: String, required: true, select: false }, uploadStatus: { type: String, enum: ['pending', 'uploaded', 'failed', 'quarantined', 'deleted'], default: 'pending' }, scanStatus: { type: String, enum: ['pending', 'clean', 'infected', 'failed'], default: 'pending' }, version: { type: Number, default: 1 }, uploadedBy: Schema.Types.ObjectId, scanMetadata: Schema.Types.Mixed }, { timestamps: true }));
Document.schema.index({ tenantId: 1, contractId: 1, createdAt: -1 });
Document.schema.index({ tenantId: 1, contractVersionId: 1, uploadStatus: 1, scanStatus: 1 });
Document.schema.index({ tenantId: 1, checksum: 1 });
export const DocumentVersion = model('DocumentVersion', new Schema({ ...base, documentId: { type: Schema.Types.ObjectId, ref: 'Document', required: true }, version: { type: Number, required: true }, checksum: { type: String, required: true }, storageProvider: String, storageKey: { type: String, required: true, select: false }, uploadedBy: Schema.Types.ObjectId, createdAt: { type: Date, default: Date.now } }, { timestamps: false }));
DocumentVersion.schema.index({ documentId: 1, version: 1 }, { unique: true });

export const Notification = model('Notification', new Schema({ ...base, recipientUserId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, type: { type: String, required: true }, category: { type: String, required: true }, title: { type: String, required: true }, message: { type: String, required: true }, entityType: String, entityId: String, status: { type: String, enum: ['unread', 'read', 'expired'], default: 'unread' }, priority: { type: String, enum: ['low', 'normal', 'high', 'critical'], default: 'normal' }, channels: [{ type: String, enum: ['email', 'in_app', 'realtime'] }], readAt: Date, expiresAt: Date, metadata: Schema.Types.Mixed, version: { type: Number, default: 1 } }, { timestamps: true }));
Notification.schema.index({ tenantId: 1, recipientUserId: 1, status: 1, createdAt: -1 });
Notification.schema.index({ tenantId: 1, recipientUserId: 1, type: 1, createdAt: -1 });
export const NotificationPreference = model('NotificationPreference', new Schema({ ...base, userId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, categories: [String], channels: [{ type: String, enum: ['email', 'in_app', 'realtime'] }], quietHours: Schema.Types.Mixed, enabled: { type: Boolean, default: true } }, { timestamps: true }));
NotificationPreference.schema.index({ tenantId: 1, userId: 1 }, { unique: true });

export function asId(value: string): mongoose.Types.ObjectId { return new mongoose.Types.ObjectId(value); }
