import { z } from 'zod';

export type Id = string;
export type UserRole = 'system_admin' | 'legal_admin' | 'legal_counsel' | 'contract_manager' | 'business_owner' | 'auditor';
export type ContractStatus = 'draft' | 'review' | 'approval' | 'signature' | 'active' | 'monitoring' | 'renewal' | 'expired' | 'terminated' | 'archived';
export type Permission = string;
export interface User { _id: Id; email: string; profile?: { displayName?: string; firstName?: string; lastName?: string }; organization?: { name?: string }; roleIds?: Array<Id | { name?: string; key?: string }>; roles?: Array<{ name?: string; key?: string }>; status?: string; permissions?: Permission[]; version?: number; }
export interface Contract { _id: Id; contractNumber?: string; title?: string; contractType?: string; parties?: Array<Record<string, unknown>>; ownerId?: Id; departmentId?: Id; businessUnitId?: Id; status: ContractStatus; effectiveDate?: string; expiryDate?: string; financial?: { value?: string; currency?: string }; currentVersionId?: Id; version: number; createdAt?: string; updatedAt?: string; }
export interface ContractVersion { _id: Id; contractId: Id; versionNumber: number; state?: string; changeSummary?: string; authorId?: Id; createdAt?: string; }
export interface ApprovalTask { _id: Id; contractId: Id; workflowId?: Id; stageKey?: string; assigneeUserId?: Id; status: string; version: number; dueAt?: string; comments?: string[]; }
export interface Obligation { _id: Id; contractId: Id; ownerId: Id; type: string; title: string; description?: string; priority?: string; dueDate: string; status: string; version: number; }
export interface DocumentRecord { _id: Id; contractId: Id; fileName: string; originalFileName?: string; mimeType: string; sizeBytes: number; classification: string; uploadStatus: string; scanStatus: string; version: number; createdAt?: string; }
export interface NotificationRecord { _id: Id; title?: string; message?: string; category?: string; status: string; version: number; createdAt?: string; }
export interface Session { sessionId: string; userAgent?: string; ip?: string; createdAt?: string; lastSeenAt?: string; }
export interface IntelligenceTerm { name: string; value: string; confidence: number; evidence: string; }
export interface IntelligenceRisk { category: string; severity: 'low' | 'medium' | 'high' | 'critical'; title: string; explanation: string; recommendation: string; evidence: string; confidence: number; }
export interface IntelligenceCitation { label: string; evidence: string; }
export interface ContractIntelligence { _id: Id; contractId: Id; contractVersionId?: Id; kind: 'analysis' | 'question'; status: 'generated' | 'accepted' | 'overridden'; provider: string; model: string; summary?: string; keyTerms?: IntelligenceTerm[]; risks?: IntelligenceRisk[]; missingInformation?: string[]; question?: string; answer?: string; citations?: IntelligenceCitation[]; confidence?: number; needsHumanReview?: boolean; reviewedBy?: Id; reviewedAt?: string; reviewNotes?: string; createdAt?: string; }
export interface Paginated<T> { items: T[]; nextCursor?: string | null; }
export interface ApiError { code: string; message: string; fieldErrors?: Record<string, string[]>; }

const oid = z.string().regex(/^[a-f\d]{24}$/i, 'Must be a valid MongoDB id');
const iso = z.string().datetime({ offset: true });
export const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
export const contractCreateSchema = z.object({ contractNumber: z.string().min(1).max(80), title: z.string().min(1).max(240), contractType: z.string().min(1).max(80), parties: z.array(z.record(z.string(), z.unknown())).max(50), ownerId: oid.optional(), departmentId: oid.optional(), businessUnitId: oid.optional(), effectiveDate: iso.optional(), expiryDate: iso.optional(), financial: z.object({ value: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().length(3) }).optional(), metadata: z.record(z.string(), z.unknown()).optional() }).strict();
export const contractUpdateSchema = contractCreateSchema.partial().extend({ status: z.enum(['draft','review','approval','signature','active','monitoring','renewal','expired','terminated','archived']).optional(), version: z.number().int().positive() }).strict();
export const approvalActionSchema = z.object({ version: z.number().int().positive().optional(), comment: z.string().max(4000).optional(), reason: z.string().max(4000).optional(), delegateToUserId: oid.optional(), expiresAt: iso.optional() }).strict();
export const obligationCreateSchema = z.object({ contractId: oid, ownerId: oid, type: z.string().min(1).max(80), title: z.string().min(1).max(200), description: z.string().max(4000).optional(), priority: z.enum(['low','medium','high','critical']).optional(), dueDate: iso, recurrence: z.record(z.string(), z.unknown()).optional(), escalationPolicy: z.record(z.string(), z.unknown()).optional(), evidenceDocuments: z.array(z.record(z.string(), z.unknown())).max(20).optional() }).strict();
export const obligationCompleteSchema = z.object({ completionNote: z.string().min(1).max(4000), evidenceDocuments: z.array(z.record(z.string(), z.unknown())).max(20).optional(), version: z.number().int().positive() }).strict();
export const templateCreateSchema = z.object({ name: z.string().min(1).max(120), key: z.string().regex(/^[a-z0-9-]+$/), contractType: z.string().min(1), description: z.string().max(2000).optional(), clauseRefs: z.array(oid).max(200).optional(), variables: z.array(z.record(z.string(), z.unknown())).max(100).optional() }).strict();
export const clauseCreateSchema = z.object({ key: z.string().regex(/^[a-z0-9-]+$/), title: z.string().min(1).max(200), body: z.string().min(1).max(50000), category: z.string().max(80), riskClassification: z.enum(['low','medium','high','critical']), tags: z.array(z.string().max(50)).max(30).optional() }).strict();
export const workflowCreateSchema = z.object({ name: z.string().min(1).max(120), key: z.string().regex(/^[a-z0-9-]+$/), contractType: z.string().optional(), triggerRules: z.array(z.record(z.string(), z.unknown())).max(20), stages: z.array(z.object({ stageKey: z.string(), assignedUserId: oid.optional(), assignedRoleId: oid.optional(), slaHours: z.number().int().positive().max(8760).optional(), quorum: z.number().int().positive().max(100).optional(), escalation: z.record(z.string(), z.unknown()).optional() }).strict()).min(1).max(30), rejectionPolicy: z.record(z.string(), z.unknown()).optional() }).strict();
export const notificationPreferencesSchema = z.object({ categories: z.array(z.string().min(1).max(80)).max(50), channels: z.array(z.enum(['email','in_app','realtime'])).min(1).max(3), quietHours: z.object({ start: z.string().regex(/^\d{2}:\d{2}$/), end: z.string().regex(/^\d{2}:\d{2}$/) }).optional(), enabled: z.boolean() }).strict();
export const intelligenceAnalyzeSchema = z.object({ playbook: z.array(z.string().min(1).max(1000)).max(100).optional() }).strict();
export const intelligenceQuestionSchema = z.object({ question: z.string().min(3).max(2000), intelligenceId: oid.optional() }).strict();
export const intelligenceReviewSchema = z.object({ decision: z.enum(['accepted', 'overridden']), notes: z.string().max(4000).optional() }).strict();
export const documentUploadSchema = z.object({ contractId: oid, versionId: oid.optional(), obligationId: oid.optional(), documentType: z.string().min(1).max(80), fileName: z.string().regex(/^[^/\\]{1,255}$/), mimeType: z.enum(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain']), sizeBytes: z.number().int().positive().max(50 * 1024 * 1024), checksum: z.string().regex(/^[a-f\d]{64}$/i), classification: z.enum(['public','internal','confidential','restricted']) }).strict();
export function parseForm<T>(schema: z.ZodType<T>, value: unknown): T { return schema.parse(value); }
