import { Contract, ApprovalTask, Obligation, DashboardProjection } from '../models/index.js';
import { redis } from '../config/connections.js';

const ttlSeconds = 60;
const key = (tenantId: string, type: string) => `covenx:dashboard:${tenantId}:${type}`;
async function cacheGet<T>(cacheKey: string): Promise<T | null> { try { if ((redis as any).status !== 'ready') return null; const value = await redis.get(cacheKey); return value ? JSON.parse(value) as T : null; } catch { return null; } }
async function cacheSet(cacheKey: string, value: any) { try { if ((redis as any).status === 'ready') await redis.set(cacheKey, JSON.stringify(value), 'EX', ttlSeconds); } catch { /* Redis failure must not break reporting. */ } }
export async function invalidateDashboardCache(tenantId: string) { try { if ((redis as any).status === 'ready') { const keys = await redis.keys(`covenx:dashboard:${tenantId}:*`); if (keys.length) await redis.del(...keys); } } catch { /* safe fallback */ } }
async function summaryFromDb(tenantId: string) { const [contracts, values, expirations, overdueObligations, pendingApprovals] = await Promise.all([Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: '$status', count: { $sum: 1 } } }]), Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: null, total: { $sum: { $toDouble: { $ifNull: ['$financial.value', '0'] } } } } }]), Contract.countDocuments({ tenantId, expiryDate: { $gte: new Date(), $lte: new Date(Date.now() + 90 * 86400000) } }), Obligation.countDocuments({ tenantId, status: 'overdue' }), ApprovalTask.countDocuments({ tenantId, status: { $in: ['pending', 'in_progress', 'delegated'] } })]); const byStatus = Object.fromEntries(contracts.map((x: any) => [x._id, x.count])); return { totalContracts: contracts.reduce((sum: number, x: any) => sum + x.count, 0), activeContracts: byStatus.active ?? 0, contractsByLifecycleStatus: byStatus, totalContractValue: values[0]?.total ?? 0, upcomingExpirations: expirations, overdueObligations, pendingApprovals, complianceIndicators: { obligationCompliance: await obligationCompliance(tenantId) }, generatedAt: new Date(), dataAsOf: new Date(), cacheStatus: 'miss' }; }
async function obligationCompliance(tenantId: string) { const [total, completed] = await Promise.all([Obligation.countDocuments({ tenantId }), Obligation.countDocuments({ tenantId, status: 'completed' })]); return total ? Math.round((completed / total) * 10000) / 100 : 100; }
export async function getDashboardSummary(tenantId: string) { const cacheKey = key(tenantId, 'summary'); const cached = await cacheGet<any>(cacheKey); if (cached) return { ...cached, cacheStatus: 'hit' }; const value = await summaryFromDb(tenantId); await cacheSet(cacheKey, value); return value; }
export async function getContractAnalytics(tenantId: string) { const cacheKey = key(tenantId, 'contracts'); const cached = await cacheGet<any>(cacheKey); if (cached) return { ...cached, cacheStatus: 'hit' }; const [byStatus, byType, byDepartment, byBusinessUnit, values, expiry] = await Promise.all([Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: '$status', count: { $sum: 1 } } }]), Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: '$contractType', count: { $sum: 1 } } }]), Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: '$departmentId', count: { $sum: 1 } } }]), Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: '$businessUnitId', count: { $sum: 1 } } }]), Contract.aggregate([{ $match: { tenantId } }, { $group: { _id: null, total: { $sum: { $toDouble: { $ifNull: ['$financial.value', '0'] } } } } }]), Contract.aggregate([{ $match: { tenantId, expiryDate: { $ne: null } } }, { $bucket: { groupBy: '$expiryDate', boundaries: [new Date(), new Date(Date.now() + 30 * 86400000), new Date(Date.now() + 90 * 86400000), new Date(Date.now() + 365 * 86400000)], default: 'later', output: { count: { $sum: 1 } } } }])]); const value = { contractsByStatus: byStatus, contractsByType: byType, contractsByDepartment: byDepartment, contractsByBusinessUnit: byBusinessUnit, contractValues: values[0]?.total ?? 0, expiryDistribution: expiry, generatedAt: new Date(), dataAsOf: new Date(), cacheStatus: 'miss' }; await cacheSet(cacheKey, value); return value; }
export async function getApprovalAnalytics(tenantId: string) { const [pending, overdue] = await Promise.all([ApprovalTask.countDocuments({ tenantId, status: { $in: ['pending', 'in_progress', 'delegated'] } }), ApprovalTask.countDocuments({ tenantId, status: { $in: ['pending', 'in_progress', 'delegated'] }, dueAt: { $lt: new Date() } })]); return { pendingApprovals: pending, overdueApprovals: overdue, approvalCycleTime: null, rejectionRates: null, averageApprovalDuration: null, generatedAt: new Date(), dataAsOf: new Date(), cacheStatus: 'miss' }; }
export async function getObligationAnalytics(tenantId: string) { const [total, completed, overdue, upcoming] = await Promise.all([Obligation.countDocuments({ tenantId }), Obligation.countDocuments({ tenantId, status: 'completed' }), Obligation.countDocuments({ tenantId, status: 'overdue' }), Obligation.countDocuments({ tenantId, dueDate: { $gte: new Date(), $lte: new Date(Date.now() + 30 * 86400000) } })]); return { totalObligations: total, completedObligations: completed, overdueObligations: overdue, compliancePercentage: total ? Math.round(completed / total * 10000) / 100 : 100, upcomingDeadlines: upcoming, generatedAt: new Date(), dataAsOf: new Date(), cacheStatus: 'miss' }; }
export async function updateDashboardProjection(tenantId: string, projectionType = 'summary') { const metrics = projectionType === 'summary' ? await summaryFromDb(tenantId) : await getContractAnalytics(tenantId); return DashboardProjection.findOneAndUpdate({ tenantId, projectionType, 'scope.key': 'tenant' }, { $set: { tenantId, projectionType, scope: { key: 'tenant' }, metrics, generatedAt: new Date(), dataAsOf: new Date() }, $inc: { version: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); }
