import { Notification, NotificationPreference } from '../models/index.js';
import { publishEvent } from './events.js';

export interface NotificationProvider { sendInApp(notification: any): Promise<void>; sendEmail(notification: any): Promise<void>; sendRealtime(notification: any): Promise<void>; }
export interface RealtimeNotificationProvider { emitToUser(userId: string, tenantId: string, payload: any): Promise<void>; emitToTenant(tenantId: string, payload: any): Promise<void>; }
export class MockNotificationProvider implements NotificationProvider { sent: any[] = []; async sendInApp(n: any) { this.sent.push({ channel: 'in_app', id: String(n._id) }); } async sendEmail(n: any) { this.sent.push({ channel: 'email', id: String(n._id) }); } async sendRealtime(n: any) { this.sent.push({ channel: 'realtime', id: String(n._id) }); } }
export class MockRealtimeNotificationProvider implements RealtimeNotificationProvider { emitted: any[] = []; async emitToUser(userId: string, tenantId: string, payload: any) { this.emitted.push({ target: 'user', userId, tenantId, payload }); } async emitToTenant(tenantId: string, payload: any) { this.emitted.push({ target: 'tenant', tenantId, payload }); } }
export const notificationProvider = new MockNotificationProvider();
export const realtimeProvider = new MockRealtimeNotificationProvider();
export async function createNotification(input: any) { const preference: any = await NotificationPreference.findOne({ tenantId: input.tenantId, userId: input.recipientUserId }); const enabled = preference?.enabled !== false; const categories = preference?.categories?.length ? preference.categories : undefined; if (!enabled || (categories && !categories.includes(input.category))) return null; const duplicate = await Notification.findOne({ tenantId: input.tenantId, recipientUserId: input.recipientUserId, type: input.type, entityType: input.entityType, entityId: input.entityId, createdAt: { $gte: new Date(Date.now() - 60 * 60_000) } }); if (duplicate) return duplicate; const channels = preference?.channels?.length ? preference.channels : ['in_app', 'realtime']; const notification = await Notification.create({ ...input, channels, status: 'unread' }); await publishEvent({ name: 'NotificationCreated.v1', tenantId: input.tenantId, actorId: input.actorId, entityId: notification.id, requestId: input.requestId, payload: { notificationId: notification.id, recipientUserId: String(input.recipientUserId), type: input.type, entityType: input.entityType, entityId: input.entityId } }); return notification; }
export async function deliverNotification(notification: any) { for (const channel of notification.channels ?? []) { if (channel === 'in_app') await notificationProvider.sendInApp(notification); if (channel === 'email') await notificationProvider.sendEmail(notification); if (channel === 'realtime') { await notificationProvider.sendRealtime(notification); await realtimeProvider.emitToUser(String(notification.recipientUserId), String(notification.tenantId), { notificationId: String(notification._id), type: notification.type }); } } }
