import { ApprovalTask, Contract, Obligation, SignatureParticipant } from '../models/index.js';
import { claimPendingEvents, markEventFailed, markEventPublished } from './events.js';
import { createNotification, deliverNotification } from './notifications.js';
import { findRenewalsDue, emitRenewalDue } from './renewals.js';

export async function handleDomainEvent(event: any) {
  const p = event.payload ?? {};
  if (event.name === 'ApprovalCreated.v1') { const task: any = await ApprovalTask.findById(event.entityId); if (task?.assignedUserId) { const n = await createNotification({ tenantId: event.tenantId, recipientUserId: task.assignedUserId, type: 'approval_task_created', category: 'approvals', title: 'Approval task assigned', message: 'A contract approval task requires your review.', entityType: 'approvalTask', entityId: String(task._id), actorId: event.actorId, requestId: event.requestId }); if (n) await deliverNotification(n); } }
  if (event.name === 'SignatureCompleted.v1') { const participants: any[] = await SignatureParticipant.find({ signatureRequestId: p.signatureRequestId, status: 'pending' }); for (const participant of participants) { if (participant.userId) { const n = await createNotification({ tenantId: event.tenantId, recipientUserId: participant.userId, type: 'signature_required', category: 'signatures', title: 'Signature required', message: 'A contract is waiting for your signature.', entityType: 'signatureRequest', entityId: String(p.signatureRequestId), actorId: event.actorId, requestId: event.requestId }); if (n) await deliverNotification(n); } } }
  if (event.name === 'ObligationCreated.v1' || event.name === 'RenewalDue.v1') { const userId = p.ownerId ?? event.actorId; if (userId) { const n = await createNotification({ tenantId: event.tenantId, recipientUserId: userId, type: event.name === 'RenewalDue.v1' ? 'renewal_due' : 'obligation_created', category: event.name === 'RenewalDue.v1' ? 'renewals' : 'obligations', title: event.name === 'RenewalDue.v1' ? 'Renewal due' : 'Obligation created', message: event.name === 'RenewalDue.v1' ? 'A contract is approaching expiry.' : 'A new obligation has been assigned.', entityType: event.name === 'RenewalDue.v1' ? 'contract' : 'obligation', entityId: event.entityId, actorId: event.actorId, requestId: event.requestId }); if (n) await deliverNotification(n); } }
}

export async function dispatchOutboxBatch(limit = 25) { const processed: string[] = []; for (let i = 0; i < limit; i += 1) { const event: any = await claimPendingEvents(); if (!event) break; try { await handleDomainEvent(event); await markEventPublished(event.eventId); processed.push(event.eventId); } catch (error: any) { await markEventFailed(event.eventId, error?.message ?? 'Event handler failed'); } } return processed; }
export async function runObligationReminderWorker(tenantId: string, days = 7) { const cutoff = new Date(Date.now() + days * 86400000); const obligations: any[] = await Obligation.find({ tenantId, status: { $in: ['open', 'in_progress'] }, dueDate: { $lte: cutoff } }); let count = 0; for (const obligation of obligations) { const n = await createNotification({ tenantId, recipientUserId: obligation.ownerId, type: obligation.dueDate < new Date() ? 'obligation_overdue' : 'obligation_due', category: 'obligations', title: obligation.dueDate < new Date() ? 'Obligation overdue' : 'Obligation due soon', message: 'Review the obligation timeline and required evidence.', entityType: 'obligation', entityId: String(obligation._id), actorId: 'system' }); if (n) { await deliverNotification(n); count++; } } return count; }
export async function runRenewalReminderWorker(tenantId: string, days = 90) { const contracts: any[] = await findRenewalsDue(tenantId, days); for (const contract of contracts) await emitRenewalDue(contract); return contracts.length; }
export async function runApprovalSlaWorker(tenantId: string) { const tasks: any[] = await ApprovalTask.find({ tenantId, status: { $in: ['pending', 'in_progress', 'delegated'] }, dueAt: { $lt: new Date() } }); let count = 0; for (const task of tasks) { if (task.assignedUserId) { const n = await createNotification({ tenantId, recipientUserId: task.assignedUserId, type: 'approval_overdue', category: 'approvals', title: 'Approval overdue', message: 'An approval task has exceeded its SLA.', entityType: 'approvalTask', entityId: String(task._id), actorId: 'system' }); if (n) { await deliverNotification(n); count++; } } } return count; }
