import { Router, Request } from 'express';
import { z } from 'zod';
import { User, Role, Permission, Contract, ContractVersion, AuditLog, Template, TemplateVersion, Clause, ClauseVersion, Workflow, WorkflowVersion, ApprovalTask, asId } from '../models/index.js';
import { hashPassword, signIn, rotateRefresh, writeAudit } from '../services/auth.js';
import { assertTransition } from '../services/lifecycle.js';
import { requireAuth, requirePermission, validate } from '../middleware/index.js';

const router = Router();
const tenant = (req: Request) => String(req.auth?.tenantId ?? req.header('x-tenant-id') ?? '000000000000000000000001');
const envelope = (data: any, req: Request) => ({ success: true, data, meta: { requestId: req.requestId } });
const userView = (u: any) => { const value = u.toObject ? u.toObject() : { ...u }; delete value.passwordHash; return value; };

router.post('/auth/login', validate(z.object({ body: z.object({ email: z.string().email(), password: z.string().min(8) }), params: z.any(), query: z.any() })), async (req, res, next) => { try { const result = await signIn(req.body.email, req.body.password, tenant(req), { ip: req.ip, userAgent: req.get('user-agent'), requestId: req.requestId }); res.cookie('refresh_token', `${result.sessionId}.${result.refreshToken}`, { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 30 * 86400000 }); res.json(envelope({ user: userView(result.user), accessToken: result.accessToken, sessionId: result.sessionId }, req)); } catch (e) { next(e); } });
router.post('/auth/refresh', async (req, res, next) => { try { const value = req.cookies?.refresh_token as string | undefined; if (!value) throw new Error('TOKEN_INVALID'); const [sessionId, token] = value.split('.'); const nextToken = await rotateRefresh(sessionId, token); res.cookie('refresh_token', `${sessionId}.${nextToken}`, { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 30 * 86400000 }); res.json(envelope({ sessionId, rotated: true }, req)); } catch (e) { next(e); } });
router.post('/auth/logout', requireAuth, async (req, res, next) => { try { const value = req.cookies?.refresh_token as string | undefined; if (value) { const [sessionId] = value.split('.'); const { redis } = await import('../config/connections.js'); await redis.del(`refresh:${sessionId}`); } res.clearCookie('refresh_token'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'auth.logout', entity: { type: 'user', id: req.auth!.userId }, result: 'success', requestId: req.requestId }); res.status(204).end(); } catch (e) { next(e); } });
router.get('/auth/me', requireAuth, async (req, res, next) => { try { const user = await User.findOne({ _id: asId(req.auth!.userId), tenantId: tenant(req) }).populate({ path: 'roleIds', populate: { path: 'permissionIds' } }); if (!user) throw Object.assign(new Error('RESOURCE_NOT_FOUND'), { status: 404 }); res.json(envelope({ user: userView(user), roles: user.roleIds, permissions: req.auth!.permissions }, req)); } catch (e) { next(e); } });

router.post('/auth/register', requireAuth, requirePermission('user:create'), validate(z.object({ body: z.object({ email: z.string().email(), password: z.string().min(8), firstName: z.string().min(1), lastName: z.string().min(1), roleIds: z.array(z.string()).optional(), departmentId: z.string().optional(), businessUnitIds: z.array(z.string()).optional() }), params: z.any(), query: z.any() })), async (req, res, next) => { try { const t = tenant(req); const user = await User.create({ tenantId: t, email: req.body.email, normalizedEmail: req.body.email.toLowerCase(), passwordHash: await hashPassword(req.body.password), profile: { firstName: req.body.firstName, lastName: req.body.lastName, displayName: `${req.body.firstName} ${req.body.lastName}` }, organization: { departmentId: req.body.departmentId, businessUnitIds: req.body.businessUnitIds }, roleIds: (req.body.roleIds ?? []).map(asId), status: 'active' }); await writeAudit({ tenantId: t, actorId: req.auth!.userId, action: 'user.created', entity: { type: 'user', id: user.id }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope(userView(user), req)); } catch (e) { next(e); } });

router.get('/users', requireAuth, requirePermission('user:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.status) filter.status = req.query.status; if (req.query.q) filter.$or = [{ normalizedEmail: new RegExp(String(req.query.q).toLowerCase(), 'i') }, { 'profile.displayName': new RegExp(String(req.query.q), 'i') }]; const data = await User.find(filter).select('-passwordHash').sort({ updatedAt: -1, _id: -1 }).limit(Math.min(Number(req.query.limit) || 25, 100)); res.json(envelope(data.map(userView), req)); } catch (e) { next(e); } });
router.get('/users/:id', requireAuth, requirePermission('user:read'), async (req, res, next) => { try { const user = await User.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('-passwordHash'); if (!user) return res.status(404).json({ success: false, error: { code: 'USER_NOT_FOUND', message: 'User not found' } }); res.json(envelope(userView(user), req)); } catch (e) { next(e); } });
router.patch('/users/:id', requireAuth, requirePermission('user:update'), async (req, res, next) => { try { const allowed = ['profile', 'organization', 'roleIds', 'status']; const update: any = {}; for (const key of allowed) if (req.body[key] !== undefined) update[key] = key === 'roleIds' ? req.body[key].map(asId) : req.body[key]; update.updatedAt = new Date(); const user = await User.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req) }, { $set: update, $inc: { authVersion: update.status ? 1 : 0 } }, { new: true }).select('-passwordHash'); if (!user) return res.status(404).json({ success: false, error: { code: 'USER_NOT_FOUND', message: 'User not found' } }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'user.updated', entity: { type: 'user', id: user.id }, newValue: update, result: 'success', requestId: req.requestId }); res.json(envelope(userView(user), req)); } catch (e) { next(e); } });
router.delete('/users/:id', requireAuth, requirePermission('user:manage'), async (req, res, next) => { try { const user = await User.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req) }, { $set: { status: 'deactivated', updatedAt: new Date() }, $inc: { authVersion: 1 } }, { new: true }); if (!user) return res.status(404).end(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'user.deactivated', entity: { type: 'user', id: user.id }, result: 'success' }); res.status(204).end(); } catch (e) { next(e); } });

router.get('/roles', requireAuth, requirePermission('role:read'), async (req, res, next) => { try { res.json(envelope(await Role.find({ tenantId: tenant(req), status: req.query.status ?? 'active' }).populate('permissionIds'), req)); } catch (e) { next(e); } });
router.post('/roles', requireAuth, requirePermission('role:create'), async (req, res, next) => { try { const role = await Role.create({ tenantId: tenant(req), name: req.body.name, key: req.body.key, permissionIds: (req.body.permissionIds ?? []).map(asId), scopeRules: req.body.scopeRules, status: 'active' }); res.status(201).json(envelope(role, req)); } catch (e) { next(e); } });
router.patch('/roles/:id', requireAuth, requirePermission('role:update'), async (req, res, next) => { try { const update: any = { ...req.body, updatedAt: new Date() }; if (update.permissionIds) update.permissionIds = update.permissionIds.map(asId); const role = await Role.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req) }, { $set: update }, { new: true }); if (!role) return res.status(404).end(); res.json(envelope(role, req)); } catch (e) { next(e); } });
router.get('/permissions', requireAuth, requirePermission('permission:read'), async (req, res, next) => { try { res.json(envelope(await Permission.find({ status: req.query.status ?? 'active' }), req)); } catch (e) { next(e); } });

router.get('/contracts', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; for (const field of ['status', 'contractType', 'ownerId', 'departmentId', 'businessUnitId']) if (req.query[field]) filter[field] = req.query[field]; if (req.query.q) filter.$text = { $search: String(req.query.q) }; const data = await Contract.find(filter).sort({ updatedAt: -1, _id: -1 }).limit(Math.min(Number(req.query.limit) || 25, 100)); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/contracts', requireAuth, requirePermission('contract:create'), async (req, res, next) => { try { const contract = await Contract.create({ ...req.body, tenantId: tenant(req), ownerId: asId(req.body.ownerId ?? req.auth!.userId), status: 'draft' }); const version = await ContractVersion.create({ tenantId: tenant(req), contractId: contract.id, versionNumber: 1, state: 'draft', authorId: req.auth!.userId, changeSummary: 'Initial draft' }); contract.currentVersionId = version.id; await contract.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.created', entity: { type: 'contract', id: contract.id }, newValue: { status: 'draft' }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope(contract, req)); } catch (e) { next(e); } });
router.get('/contracts/:id', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const c = await Contract.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!c) return res.status(404).json({ success: false, error: { code: 'CONTRACT_NOT_FOUND', message: 'Contract not found' } }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.patch('/contracts/:id', requireAuth, requirePermission('contract:update'), async (req, res, next) => { try { const c = await Contract.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!c) return res.status(404).end(); if (c.status !== 'draft' && c.status !== 'review') throw new Error('CONFLICT'); const expected = Number(req.body.version ?? c.version); if (expected !== c.version) throw new Error('VERSION_CONFLICT'); Object.assign(c, req.body); c.version += 1; await c.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.updated', entity: { type: 'contract', id: c.id }, result: 'success', requestId: req.requestId }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.delete('/contracts/:id', requireAuth, requirePermission('contract:delete'), async (req, res, next) => { try { const c = await Contract.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: 'draft' }, { $set: { status: 'archived', updatedAt: new Date() } }, { new: true }); if (!c) return res.status(404).json({ success: false, error: { code: 'CONTRACT_NOT_FOUND', message: 'Draft contract not found' } }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.deleted', entity: { type: 'contract', id: c.id }, result: 'success' }); res.status(204).end(); } catch (e) { next(e); } });
router.post('/contracts/:id/submit-review', requireAuth, requirePermission('contract:submit-review'), async (req, res, next) => { try { assertTransition('draft', 'review'); const c = await Contract.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: 'draft', version: Number(req.body.version) }, { $set: { status: 'review', updatedAt: new Date() }, $inc: { version: 1 } }, { new: true }); if (!c) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.submitted', entity: { type: 'contract', id: c.id }, result: 'success' }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/archive', requireAuth, requirePermission('contract:archive'), async (req, res, next) => { try { const c = await Contract.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: { $in: ['active', 'monitoring', 'renewal'] }, version: Number(req.body.version) }, { $set: { status: 'archived', updatedAt: new Date() }, $inc: { version: 1 } }, { new: true }); if (!c) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.archived', entity: { type: 'contract', id: c.id }, result: 'success' }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/renew', requireAuth, requirePermission('contract:renew'), async (req, res, next) => { try { const current = await Contract.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: { $in: ['active', 'monitoring', 'renewal'] } }); if (!current) return res.status(404).json({ success: false, error: { code: 'CONTRACT_NOT_FOUND', message: 'Contract not found' } }); const version = await ContractVersion.findOne({ _id: current.currentVersionId, tenantId: tenant(req) }); const renewal = await Contract.create({ ...current.toObject(), _id: undefined, contractNumber: `${current.contractNumber}-R${Date.now()}`, status: 'renewal', version: 1, currentVersionId: undefined, renewal: { ...(current.renewal as any ?? {}), sourceContractId: current.id, targetExpiryDate: req.body.targetExpiryDate } }); const renewalVersion = await ContractVersion.create({ tenantId: tenant(req), contractId: renewal.id, versionNumber: 1, state: 'draft', authorId: req.auth!.userId, previousVersionId: version?._id, changeSummary: 'Renewal draft' }); renewal.currentVersionId = renewalVersion.id; await renewal.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.renewal_started', entity: { type: 'contract', id: renewal.id }, metadata: { sourceContractId: current.id }, result: 'success' }); res.status(201).json(envelope(renewal, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/history', requireAuth, requirePermission('contract:history'), async (req, res, next) => { try { const events = await AuditLog.find({ tenantId: tenant(req), 'entity.type': 'contract', 'entity.id': String(req.params.id) }).sort({ timestamp: -1 }).limit(Math.min(Number(req.query.limit) || 50, 100)); res.json(envelope(events, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/versions', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { res.json(envelope(await ContractVersion.find({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ versionNumber: -1 }), req)); } catch (e) { next(e); } });
router.post('/contracts/:id/versions', requireAuth, requirePermission('contract:update'), async (req, res, next) => { try { const previous = await ContractVersion.findOne({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ versionNumber: -1 }); const v = await ContractVersion.create({ tenantId: tenant(req), contractId: asId(String(req.params.id)), versionNumber: (previous?.versionNumber ?? 0) + 1, state: 'draft', authorId: req.auth!.userId, previousVersionId: previous?._id, changeSummary: req.body.changeSummary, contentRef: req.body.contentRef }); res.status(201).json(envelope(v, req)); } catch (e) { next(e); } });
router.get('/audit', requireAuth, requirePermission('audit:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.action) filter.action = req.query.action; if (req.query.actorId) filter.actorId = req.query.actorId; const events = await AuditLog.find(filter).sort({ timestamp: -1 }).limit(Math.min(Number(req.query.limit) || 50, 100)); res.json(envelope(events, req)); } catch (e) { next(e); } });

router.get('/templates', requireAuth, requirePermission('template:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.contractType) filter.contractType = req.query.contractType; if (req.query.status) filter.status = req.query.status; res.json(envelope(await Template.find(filter).sort({ updatedAt: -1 }).limit(100), req)); } catch (e) { next(e); } });
router.post('/templates', requireAuth, requirePermission('template:create'), async (req, res, next) => { try { const template = await Template.create({ ...req.body, tenantId: tenant(req), ownerId: req.auth!.userId, status: 'draft' }); await TemplateVersion.create({ tenantId: tenant(req), templateId: template.id, versionNumber: 1, status: 'draft', clauseRefs: req.body.clauseRefs ?? [], variables: req.body.variables ?? [], authorId: req.auth!.userId }); res.status(201).json(envelope(template, req)); } catch (e) { next(e); } });
router.get('/templates/:id', requireAuth, requirePermission('template:read'), async (req, res, next) => { try { const t = await Template.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!t) return res.status(404).end(); res.json(envelope(t, req)); } catch (e) { next(e); } });
router.patch('/templates/:id', requireAuth, requirePermission('template:update'), async (req, res, next) => { try { const t = await Template.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!t) return res.status(404).end(); if (t.status === 'published' && req.body.status === 'published') throw new Error('CONFLICT'); Object.assign(t, req.body); await t.save(); if (req.body.status === 'published') await TemplateVersion.updateOne({ templateId: t.id, versionNumber: t.currentVersion }, { $set: { status: 'published', publishedAt: new Date() } }); res.json(envelope(t, req)); } catch (e) { next(e); } });

router.get('/clauses', requireAuth, requirePermission('clause:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; for (const field of ['category', 'riskClassification', 'status']) if (req.query[field]) filter[field] = req.query[field]; if (req.query.q) filter.$or = [{ title: new RegExp(String(req.query.q), 'i') }, { body: new RegExp(String(req.query.q), 'i') }]; res.json(envelope(await Clause.find(filter).sort({ updatedAt: -1 }).limit(100), req)); } catch (e) { next(e); } });
router.post('/clauses', requireAuth, requirePermission('clause:create'), async (req, res, next) => { try { const clause = await Clause.create({ ...req.body, tenantId: tenant(req), ownerId: req.auth!.userId, status: 'draft', versionNumber: 1 }); await ClauseVersion.create({ tenantId: tenant(req), clauseId: clause.id, versionNumber: 1, body: clause.body, status: 'draft', authorId: req.auth!.userId }); res.status(201).json(envelope(clause, req)); } catch (e) { next(e); } });
router.patch('/clauses/:id', requireAuth, requirePermission('clause:update'), async (req, res, next) => { try { const clause = await Clause.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!clause) return res.status(404).end(); if (clause.status === 'approved' && req.body.status === 'approved') throw new Error('CONFLICT'); Object.assign(clause, req.body); clause.versionNumber += 1; await clause.save(); await ClauseVersion.create({ tenantId: tenant(req), clauseId: clause.id, versionNumber: clause.versionNumber, body: clause.body, status: clause.status, authorId: req.auth!.userId, approvedBy: clause.status === 'approved' ? req.auth!.userId : undefined, publishedAt: clause.status === 'approved' ? new Date() : undefined }); res.json(envelope(clause, req)); } catch (e) { next(e); } });

router.get('/workflows', requireAuth, requirePermission('workflow:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.status) filter.status = req.query.status; if (req.query.contractType) filter.contractType = req.query.contractType; res.json(envelope(await Workflow.find(filter).sort({ updatedAt: -1 }).limit(100), req)); } catch (e) { next(e); } });
router.post('/workflows', requireAuth, requirePermission('workflow:create'), async (req, res, next) => { try { const workflow = await Workflow.create({ ...req.body, tenantId: tenant(req), ownerId: req.auth!.userId, status: 'draft' }); await WorkflowVersion.create({ tenantId: tenant(req), workflowId: workflow.id, versionNumber: 1, status: 'draft', triggerRules: req.body.triggerRules ?? [], stages: req.body.stages ?? [], rejectionPolicy: req.body.rejectionPolicy, authorId: req.auth!.userId }); res.status(201).json(envelope(workflow, req)); } catch (e) { next(e); } });
router.get('/workflows/:id', requireAuth, requirePermission('workflow:read'), async (req, res, next) => { try { const workflow = await Workflow.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!workflow) return res.status(404).end(); res.json(envelope(workflow, req)); } catch (e) { next(e); } });
router.patch('/workflows/:id', requireAuth, requirePermission('workflow:update'), async (req, res, next) => { try { const workflow = await Workflow.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!workflow) return res.status(404).end(); if (workflow.status === 'published') throw new Error('CONFLICT'); Object.assign(workflow, req.body); await workflow.save(); if (req.body.status === 'published') await WorkflowVersion.updateOne({ workflowId: workflow.id, versionNumber: workflow.currentVersion }, { $set: { status: 'published', publishedAt: new Date() } }); res.json(envelope(workflow, req)); } catch (e) { next(e); } });

router.get('/contracts/:id/approvals', requireAuth, requirePermission('approval:read'), async (req, res, next) => { try { const tasks = await ApprovalTask.find({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ createdAt: 1 }); res.json(envelope(tasks, req)); } catch (e) { next(e); } });
router.post('/approvals/:id/approve', requireAuth, requirePermission('approval:approve'), async (req, res, next) => { try { const task = await ApprovalTask.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), assignedUserId: asId(req.auth!.userId), status: { $in: ['pending', 'in_progress'] }, version: Number(req.body.version ?? 1) }, { $set: { status: 'approved', comments: req.body.comment, completedAt: new Date() }, $inc: { version: 1 } }, { new: true }); if (!task) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'approval.approved', entity: { type: 'approvalTask', id: task.id }, newValue: { status: 'approved' }, result: 'success' }); res.json(envelope(task, req)); } catch (e) { next(e); } });
router.post('/approvals/:id/reject', requireAuth, requirePermission('approval:reject'), async (req, res, next) => { try { if (!req.body.reason) return res.status(400).json({ success: false, error: { code: 'APPROVAL_REASON_REQUIRED', message: 'Rejection reason is required' } }); const task = await ApprovalTask.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), assignedUserId: asId(req.auth!.userId), status: { $in: ['pending', 'in_progress'] }, version: Number(req.body.version ?? 1) }, { $set: { status: 'rejected', comments: req.body.reason, completedAt: new Date() }, $inc: { version: 1 } }, { new: true }); if (!task) throw new Error('CONFLICT'); await Contract.updateOne({ _id: task.contractId, tenantId: tenant(req) }, { $set: { status: 'review' }, $inc: { version: 1 } }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'approval.rejected', entity: { type: 'approvalTask', id: task.id }, newValue: { status: 'rejected', reason: req.body.reason }, result: 'success' }); res.json(envelope(task, req)); } catch (e) { next(e); } });
router.post('/approvals/:id/delegate', requireAuth, requirePermission('approval:delegate'), async (req, res, next) => { try { const task = await ApprovalTask.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), assignedUserId: asId(req.auth!.userId), status: { $in: ['pending', 'in_progress'] } }, { $set: { assignedUserId: asId(req.body.delegateToUserId), status: 'delegated', comments: req.body.reason } }, { new: true }); if (!task) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'approval.delegated', entity: { type: 'approvalTask', id: task.id }, result: 'success' }); res.json(envelope(task, req)); } catch (e) { next(e); } });

export default router;
