import { Router, Request } from 'express';
import crypto from 'node:crypto';
import { z } from 'zod';
import { User, Role, Permission, Contract, ContractVersion, CollaborationComment, AuditLog, Template, TemplateVersion, Clause, ClauseVersion, Workflow, WorkflowVersion, ApprovalTask, SignatureRequest, SignatureParticipant, Obligation, Document, DocumentVersion, Notification, NotificationPreference, IntakeRequest, IntakeQuestionnaire, Integration, WebhookEvent, asId } from '../models/index.js';
import { hashPassword, signIn, rotateRefresh, issueAccessToken, writeAudit, listSessions, revokeSession } from '../services/auth.js';
import { assertTransition } from '../services/lifecycle.js';
import { executeWorkflow, completeApproval } from '../services/workflow.js';
import { publishEvent } from '../services/events.js';
import { requestSignature, completeSignature, declineSignature } from '../services/signatures.js';
import { analyzeContract, answerContractQuestion, listContractIntelligence, reviewIntelligence } from '../services/intelligence.js';
import { createRenewal } from '../services/renewals.js';
import { compareVersions, createRedline, resolveComment } from '../services/collaboration.js';
import { indexDocument, semanticSearch as runSemanticSearch } from '../services/ingestion.js';
import { storageProvider, documentScanner, storageKey } from '../services/storage.js';
import { createNotification } from '../services/notifications.js';
import { getDashboardSummary, getContractAnalytics, getApprovalAnalytics, getObligationAnalytics } from '../services/dashboard.js';
import { searchProvider } from '../services/search.js';
import { encryptSecret, decryptSecret, redactedIntegration, providerHealthStatus, supportedIntegrationTypes, verifyHmacSignature, verifySlackSignature } from '../services/integrations.js';
import { requireAuth, requirePermission, validate } from '../middleware/index.js';
import { idempotency } from '../middleware/idempotency.js';
import { request, contractCreate, templateCreate, clauseCreate, workflowCreate, approvalAction, signatureRequest, signatureEvidence, obligationCreate, obligationPatch, obligationComplete, renewalRequest, documentUpload, documentFinalize, documentDelete, notificationPreferences, redlineCreate, collaborationCommentCreate, collaborationCommentResolve, semanticSearch } from '../validators/index.js';
import { decodeCursor, encodeCursor, pageLimit, queryFingerprint } from '../utils/pagination.js';

const router = Router();
router.use(idempotency());
const tenant = (req: Request) => String(req.auth?.tenantId ?? req.header('x-tenant-id') ?? '000000000000000000000001');
const envelope = (data: any, req: Request) => ({ success: true, data, meta: { requestId: req.requestId } });
const userView = (u: any) => { const value = u.toObject ? u.toObject() : { ...u }; delete value.passwordHash; return value; };
const paged = (req: Request, data: any[], fingerprint: string) => { const limit = pageLimit(req.query.limit); const hasMore = data.length > limit; const items = hasMore ? data.slice(0, limit) : data; const last = items.at(-1); return { success: true, data: items, meta: { requestId: req.requestId, pagination: { nextCursor: hasMore && last ? encodeCursor({ updatedAt: new Date(last.updatedAt ?? last.timestamp ?? 0).toISOString(), id: String(last._id), fingerprint }) : null, hasMore, limit } } }; };

router.post('/auth/login', validate(z.object({ body: z.object({ email: z.string().email(), password: z.string().min(8) }), params: z.any(), query: z.any() })), async (req, res, next) => { try { const result = await signIn(req.body.email, req.body.password, tenant(req), { ip: req.ip, userAgent: req.get('user-agent'), requestId: req.requestId }); res.cookie('refresh_token', `${result.sessionId}.${result.refreshToken}`, { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 30 * 86400000 }); res.json(envelope({ user: userView(result.user), accessToken: result.accessToken, sessionId: result.sessionId }, req)); } catch (e) { next(e); } });
router.post('/auth/refresh', async (req, res, next) => { try { const value = req.cookies?.refresh_token as string | undefined; if (!value) throw new Error('TOKEN_INVALID'); const [sessionId, token] = value.split('.'); const nextToken = await rotateRefresh(sessionId, token); const raw = await (await import('../config/connections.js')).redis.get(`refresh:${sessionId}`); if (!raw) throw new Error('TOKEN_INVALID'); const record = JSON.parse(raw); const accessToken = await issueAccessToken({ userId: record.userId, tenantId: record.tenantId, sessionId, roleIds: record.roleIds ?? [], authVersion: record.authVersion ?? 1 }); res.cookie('refresh_token', `${sessionId}.${nextToken}`, { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 30 * 86400000 }); res.json(envelope({ accessToken, sessionId, rotated: true }, req)); } catch (e) { next(e); } });
router.get('/auth/sessions', requireAuth, async (req, res, next) => { try { res.json(envelope(await listSessions(req.auth!.userId, tenant(req)), req)); } catch (e) { next(e); } });
router.delete('/auth/sessions/:id', requireAuth, async (req, res, next) => { try { await revokeSession(String(req.params.id), req.auth!.userId, tenant(req)); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'auth.session_revoked', entity: { type: 'session', id: String(req.params.id) }, requestId: req.requestId, result: 'success' }); res.status(204).end(); } catch (e) { next(e); } });
router.post('/auth/logout', requireAuth, async (req, res, next) => { try { const value = req.cookies?.refresh_token as string | undefined; if (value) { const [sessionId] = value.split('.'); const { redis } = await import('../config/connections.js'); await redis.del(`refresh:${sessionId}`); } res.clearCookie('refresh_token'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'auth.logout', entity: { type: 'user', id: req.auth!.userId }, result: 'success', requestId: req.requestId }); res.status(204).end(); } catch (e) { next(e); } });
router.get('/auth/me', requireAuth, async (req, res, next) => { try { const user = await User.findOne({ _id: asId(req.auth!.userId), tenantId: tenant(req) }).populate({ path: 'roleIds', populate: { path: 'permissionIds' } }); if (!user) throw Object.assign(new Error('RESOURCE_NOT_FOUND'), { status: 404 }); res.json(envelope({ user: userView(user), roles: user.roleIds, permissions: req.auth!.permissions }, req)); } catch (e) { next(e); } });

router.post('/auth/register', requireAuth, requirePermission('user:create'), validate(z.object({ body: z.object({ email: z.string().email(), password: z.string().min(8), firstName: z.string().min(1), lastName: z.string().min(1), roleIds: z.array(z.string()).optional(), departmentId: z.string().optional(), businessUnitIds: z.array(z.string()).optional() }), params: z.any(), query: z.any() })), async (req, res, next) => { try { const t = tenant(req); const user = await User.create({ tenantId: t, email: req.body.email, normalizedEmail: req.body.email.toLowerCase(), passwordHash: await hashPassword(req.body.password), profile: { firstName: req.body.firstName, lastName: req.body.lastName, displayName: `${req.body.firstName} ${req.body.lastName}` }, organization: { departmentId: req.body.departmentId, businessUnitIds: req.body.businessUnitIds }, roleIds: (req.body.roleIds ?? []).map(asId), status: 'active' }); await writeAudit({ tenantId: t, actorId: req.auth!.userId, action: 'user.created', entity: { type: 'user', id: user.id }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope(userView(user), req)); } catch (e) { next(e); } });

router.get('/users', requireAuth, requirePermission('user:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.status) filter.status = req.query.status; if (req.query.q) filter.$or = [{ normalizedEmail: new RegExp(String(req.query.q).toLowerCase(), 'i') }, { 'profile.displayName': new RegExp(String(req.query.q), 'i') }]; const data = await User.find(filter).select('-passwordHash').sort({ updatedAt: -1, _id: -1 }).limit(Math.min(Number(req.query.limit) || 25, 100)); res.json(envelope(data.map(userView), req)); } catch (e) { next(e); } });
router.get('/users/:id', requireAuth, requirePermission('user:read'), async (req, res, next) => { try { const user = await User.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('-passwordHash'); if (!user) return res.status(404).json({ success: false, error: { code: 'USER_NOT_FOUND', message: 'User not found' } }); res.json(envelope(userView(user), req)); } catch (e) { next(e); } });
router.patch('/users/:id', requireAuth, requirePermission('user:update'), async (req, res, next) => { try { const allowed = ['profile', 'organization', 'roleIds', 'status']; const update: any = {}; for (const key of allowed) if (req.body[key] !== undefined) update[key] = key === 'roleIds' ? req.body[key].map(asId) : req.body[key]; update.updatedAt = new Date(); const user = await User.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req) }, { $set: update, $inc: { authVersion: update.status ? 1 : 0 } }, { new: true }).select('-passwordHash'); if (!user) return res.status(404).json({ success: false, error: { code: 'USER_NOT_FOUND', message: 'User not found' } }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'user.updated', entity: { type: 'user', id: user.id }, newValue: update, result: 'success', requestId: req.requestId }); res.json(envelope(userView(user), req)); } catch (e) { next(e); } });
router.delete('/users/:id', requireAuth, requirePermission('user:manage'), async (req, res, next) => { try { const user = await User.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req) }, { $set: { status: 'deactivated', updatedAt: new Date() }, $inc: { authVersion: 1 } }, { new: true }); if (!user) return res.status(404).end(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'user.deactivated', entity: { type: 'user', id: user.id }, result: 'success' }); res.status(204).end(); } catch (e) { next(e); } });

router.get('/roles', requireAuth, requirePermission('role:read'), async (req, res, next) => { try { res.json(envelope(await Role.find({ tenantId: tenant(req), status: req.query.status ?? 'active' }).populate('permissionIds'), req)); } catch (e) { next(e); } });
router.post('/roles', requireAuth, requirePermission('role:create'), async (req, res, next) => { try { const role = await Role.create({ tenantId: tenant(req), name: req.body.name, key: req.body.key, permissionIds: (req.body.permissionIds ?? []).map(asId), scopeRules: req.body.scopeRules, status: 'active' }); res.status(201).json(envelope(role, req)); } catch (e) { next(e); } });
router.patch('/roles/:id', requireAuth, requirePermission('role:update'), async (req, res, next) => { try { const update: any = { ...req.body, updatedAt: new Date() }; if (update.permissionIds) update.permissionIds = update.permissionIds.map(asId); const role = await Role.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req) }, { $set: update }, { new: true }); if (!role) return res.status(404).end(); res.json(envelope(role, req)); } catch (e) { next(e); } });
router.get('/permissions', requireAuth, requirePermission('permission:read'), async (req, res, next) => { try { res.json(envelope(await Permission.find({ status: req.query.status ?? 'active' }), req)); } catch (e) { next(e); } });

router.get('/contracts', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { if (req.query.q) return res.json(envelope(await searchProvider.search({ tenantId: tenant(req), q: String(req.query.q), limit: pageLimit(req.query.limit) }), req)); const filter: any = { tenantId: tenant(req) }; for (const field of ['status', 'contractType', 'ownerId', 'departmentId', 'businessUnitId']) if (req.query[field]) filter[field] = req.query[field]; const fingerprint = queryFingerprint({ tenant: tenant(req), filter, sort: 'updatedAt:-1,_id:-1' }); const cursor = decodeCursor(req.query.cursor); if (cursor && cursor.fingerprint !== fingerprint) throw new Error('INVALID_CURSOR'); if (cursor) filter.$or = [{ updatedAt: { $lt: new Date(cursor.updatedAt) } }, { updatedAt: new Date(cursor.updatedAt), _id: { $lt: asId(cursor.id) } }]; const data = await Contract.find(filter).sort({ updatedAt: -1, _id: -1 }).limit(pageLimit(req.query.limit) + 1); res.json(paged(req, data, fingerprint)); } catch (e) { next(e); } });
router.post('/contracts', requireAuth, requirePermission('contract:create'), validate(contractCreate), async (req, res, next) => { try { const contract = await Contract.create({ ...req.body, tenantId: tenant(req), ownerId: asId(req.body.ownerId ?? req.auth!.userId), status: 'draft' }); const version = await ContractVersion.create({ tenantId: tenant(req), contractId: contract.id, versionNumber: 1, state: 'draft', authorId: req.auth!.userId, changeSummary: 'Initial draft' }); contract.currentVersionId = version.id; await contract.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.created', entity: { type: 'contract', id: contract.id }, newValue: { status: 'draft' }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope(contract, req)); } catch (e) { next(e); } });
router.get('/contracts/:id', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const c = await Contract.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!c) return res.status(404).json({ success: false, error: { code: 'CONTRACT_NOT_FOUND', message: 'Contract not found' } }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.patch('/contracts/:id', requireAuth, requirePermission('contract:update'), async (req, res, next) => { try { const c = await Contract.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!c) return res.status(404).end(); if (c.status !== 'draft' && c.status !== 'review') throw new Error('CONFLICT'); const expected = Number(req.body.version ?? c.version); if (expected !== c.version) throw new Error('VERSION_CONFLICT'); Object.assign(c, req.body); c.version += 1; await c.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.updated', entity: { type: 'contract', id: c.id }, result: 'success', requestId: req.requestId }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.delete('/contracts/:id', requireAuth, requirePermission('contract:delete'), async (req, res, next) => { try { const c = await Contract.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: 'draft' }, { $set: { status: 'archived', updatedAt: new Date() } }, { new: true }); if (!c) return res.status(404).json({ success: false, error: { code: 'CONTRACT_NOT_FOUND', message: 'Draft contract not found' } }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.deleted', entity: { type: 'contract', id: c.id }, result: 'success' }); res.status(204).end(); } catch (e) { next(e); } });
router.post('/contracts/:id/submit-review', requireAuth, requirePermission('contract:submit-review'), async (req, res, next) => { try { assertTransition('draft', 'review'); const c = await Contract.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: 'draft', version: Number(req.body.version) }, { $set: { status: 'review', updatedAt: new Date() }, $inc: { version: 1 } }, { new: true }); if (!c) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.submitted', entity: { type: 'contract', id: c.id }, result: 'success', requestId: req.requestId }); await publishEvent({ name: 'ContractSubmitted.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: c.id, requestId: req.requestId, payload: { contractId: c.id, status: c.status } }); const execution = await executeWorkflow(c.id, req.auth!.userId, req.requestId); res.json(envelope({ contract: execution.contract, workflowId: execution.workflow.id, taskIds: execution.tasks.map((task: any) => task.id) }, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/archive', requireAuth, requirePermission('contract:archive'), async (req, res, next) => { try { const c = await Contract.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: { $in: ['active', 'monitoring', 'renewal'] }, version: Number(req.body.version) }, { $set: { status: 'archived', updatedAt: new Date() }, $inc: { version: 1 } }, { new: true }); if (!c) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.archived', entity: { type: 'contract', id: c.id }, result: 'success' }); res.json(envelope(c, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/renew', requireAuth, requirePermission('renewal:create'), validate(renewalRequest), async (req, res, next) => { try { const renewal = await createRenewal(String(req.params.id), tenant(req), req.auth!.userId, req.body.targetExpiryDate ? new Date(req.body.targetExpiryDate) : undefined, req.requestId); res.status(201).json(envelope(renewal, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/history', requireAuth, requirePermission('contract:history'), async (req, res, next) => { try { const events = await AuditLog.find({ tenantId: tenant(req), 'entity.type': 'contract', 'entity.id': String(req.params.id) }).sort({ timestamp: -1 }).limit(Math.min(Number(req.query.limit) || 50, 100)); res.json(envelope(events, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/versions', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { res.json(envelope(await ContractVersion.find({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ versionNumber: -1 }), req)); } catch (e) { next(e); } });
router.post('/contracts/:id/versions', requireAuth, requirePermission('contract:update'), async (req, res, next) => { try { const previous = await ContractVersion.findOne({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ versionNumber: -1 }); const v = await ContractVersion.create({ tenantId: tenant(req), contractId: asId(String(req.params.id)), versionNumber: (previous?.versionNumber ?? 0) + 1, state: 'draft', authorId: req.auth!.userId, previousVersionId: previous?._id, changeSummary: req.body.changeSummary, contentRef: req.body.contentRef }); res.status(201).json(envelope(v, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/compare', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const query = z.object({ fromVersionId: z.string().length(24), toVersionId: z.string().length(24) }).parse(req.query); const result = await compareVersions(tenant(req), String(req.params.id), query.fromVersionId, query.toVersionId); res.json(envelope(result, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/redlines', requireAuth, requirePermission('contract:collaborate'), validate(redlineCreate), async (req, res, next) => { try { const result = await createRedline({ tenantId: tenant(req), contractId: String(req.params.id), actorId: req.auth!.userId, baseVersionId: req.body.baseVersionId, expectedContractVersion: req.body.expectedContractVersion, changeSummary: req.body.changeSummary, operations: req.body.operations, requestId: req.requestId }); res.status(201).json(envelope(result, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/comments', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req), contractId: asId(String(req.params.id)) }; if (req.query.versionId) filter.contractVersionId = asId(String(req.query.versionId)); if (req.query.status) filter.status = String(req.query.status); const data = await CollaborationComment.find(filter).sort({ createdAt: 1 }); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/comments', requireAuth, requirePermission('contract:comment'), validate(collaborationCommentCreate), async (req, res, next) => { try { const contract = await Contract.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); const version = contract && await ContractVersion.findOne({ _id: asId(req.body.versionId), contractId: contract._id, tenantId: tenant(req) }); if (!contract || !version) throw new Error('VERSION_NOT_FOUND'); const mentions = req.body.mentions ?? []; if (mentions.length && (await User.countDocuments({ _id: { $in: mentions.map(asId) }, tenantId: tenant(req), status: 'active' })) !== mentions.length) throw new Error('MENTION_SCOPE_INVALID'); const comment = await CollaborationComment.create({ tenantId: tenant(req), contractId: contract._id, contractVersionId: version._id, parentId: req.body.parentId ? asId(req.body.parentId) : undefined, authorId: asId(req.auth!.userId), body: req.body.body, anchor: req.body.anchor, mentions: mentions.map(asId) }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.comment.created', entity: { type: 'collaborationComment', id: comment.id }, metadata: { contractId: contract.id, versionId: version.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'ContractCommentCreated.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: contract.id, requestId: req.requestId, payload: { commentId: comment.id, contractId: contract.id, versionId: version.id } }); await Promise.all(mentions.filter((userId: string) => userId !== req.auth!.userId).map((recipientUserId: string) => createNotification({ tenantId: tenant(req), recipientUserId: asId(recipientUserId), actorId: req.auth!.userId, type: 'contract.comment.mention', category: 'collaboration', title: 'You were mentioned in a contract discussion', message: `${req.body.body.slice(0, 180)}${req.body.body.length > 180 ? '…' : ''}`, entityType: 'contract', entityId: contract.id, requestId: req.requestId }))); res.status(201).json(envelope(comment, req)); } catch (e) { next(e); } });
router.post('/comments/:id/resolve', requireAuth, requirePermission('contract:resolve-comment'), validate(collaborationCommentResolve), async (req, res, next) => { try { const comment = await resolveComment(tenant(req), String(req.params.id), req.auth!.userId, req.body.version, req.requestId); res.json(envelope(comment, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/intelligence', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const data = await listContractIntelligence(tenant(req), String(req.params.id)); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/intelligence/analyze', requireAuth, requirePermission('contract:update'), async (req, res, next) => { try { const body = z.object({ playbook: z.array(z.string().min(1).max(1000)).max(100).optional() }).strict().parse(req.body); const data = await analyzeContract(tenant(req), String(req.params.id), req.auth!.userId, body.playbook ?? []); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.intelligence.analyzed', entity: { type: 'contract', id: String(req.params.id) }, metadata: { intelligenceId: data.id, provider: data.provider, model: data.model }, requestId: req.requestId, result: 'success' }); res.status(201).json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/intelligence/ask', requireAuth, requirePermission('contract:read'), async (req, res, next) => { try { const body = z.object({ question: z.string().min(3).max(2000), intelligenceId: z.string().optional() }).strict().parse(req.body); const data = await answerContractQuestion(tenant(req), String(req.params.id), req.auth!.userId, body.question, body.intelligenceId); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.intelligence.question_asked', entity: { type: 'contract', id: String(req.params.id) }, metadata: { intelligenceId: data.id }, requestId: req.requestId, result: 'success' }); res.status(201).json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/intelligence/:id/review', requireAuth, requirePermission('contract:update'), async (req, res, next) => { try { const body = z.object({ decision: z.enum(['accepted', 'overridden']), notes: z.string().max(4000).optional() }).strict().parse(req.body); const data = await reviewIntelligence(tenant(req), String(req.params.id), req.auth!.userId, body.decision, body.notes); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'contract.intelligence.reviewed', entity: { type: 'contractIntelligence', id: data.id }, metadata: { decision: body.decision }, requestId: req.requestId, result: 'success' }); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/contracts/:id/signature/request', requireAuth, requirePermission('signature:request'), validate(signatureRequest), async (req, res, next) => { try { const result = await requestSignature(String(req.params.id), tenant(req), req.auth!.userId, req.body.provider, req.body.signers, req.body.contractVersionId, new Date(req.body.expiresAt), req.requestId); res.status(201).json(envelope(result, req)); } catch (e) { next(e); } });
router.get('/contracts/:id/signatures', requireAuth, requirePermission('signature:read'), async (req, res, next) => { try { const requests = await SignatureRequest.find({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ createdAt: -1 }); const data = await Promise.all(requests.map(async (item: any) => ({ request: item, participants: await SignatureParticipant.find({ tenantId: tenant(req), signatureRequestId: item._id }).sort({ signingOrder: 1 }) }))); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/signatures/:id/complete', requireAuth, requirePermission('signature:complete'), validate(signatureEvidence), async (req, res, next) => { try { const result = await completeSignature(String(req.params.id), tenant(req), req.auth!.userId, req.body.evidenceRefs, req.requestId); res.json(envelope(result, req)); } catch (e) { next(e); } });
router.post('/signatures/:id/decline', requireAuth, requirePermission('signature:decline'), validate(request(z.object({ reason: z.string().min(1).max(4000), evidenceRefs: z.array(z.record(z.string(), z.unknown())).optional() }).strict())), async (req, res, next) => { try { const result = await declineSignature(String(req.params.id), tenant(req), req.auth!.userId, req.body.reason, req.requestId); res.json(envelope(result, req)); } catch (e) { next(e); } });
router.get('/obligations', requireAuth, requirePermission('obligation:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; for (const field of ['contractId', 'ownerId', 'status', 'priority']) if (req.query[field]) filter[field] = ['contractId', 'ownerId'].includes(field) ? asId(String(req.query[field])) : req.query[field]; if (req.query.dueBefore) filter.dueDate = { ...(filter.dueDate ?? {}), $lte: new Date(String(req.query.dueBefore)) }; if (req.query.dueAfter) filter.dueDate = { ...(filter.dueDate ?? {}), $gte: new Date(String(req.query.dueAfter)) }; const data = await Obligation.find(filter).sort({ dueDate: 1, _id: 1 }).limit(pageLimit(req.query.limit) + 1); res.json(paged(req, data, queryFingerprint({ tenant: tenant(req), filter, sort: 'dueDate:1,_id:1' }))); } catch (e) { next(e); } });
router.post('/obligations', requireAuth, requirePermission('obligation:create'), validate(obligationCreate), async (req, res, next) => { try { const contract = await Contract.findOne({ _id: asId(req.body.contractId), tenantId: tenant(req) }); const owner = await User.findOne({ _id: asId(req.body.ownerId), tenantId: tenant(req), status: 'active' }); if (!contract || !owner) throw new Error('OBLIGATION_SCOPE_INVALID'); const obligation = await Obligation.create({ ...req.body, tenantId: tenant(req), contractId: contract._id, ownerId: owner._id, dueDate: new Date(req.body.dueDate) }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'obligation.created', entity: { type: 'obligation', id: obligation.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'ObligationCreated.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: obligation.id, requestId: req.requestId, payload: { contractId: contract.id, obligationId: obligation.id } }); res.status(201).json(envelope(obligation, req)); } catch (e) { next(e); } });
router.get('/obligations/:id', requireAuth, requirePermission('obligation:read'), async (req, res, next) => { try { const obligation = await Obligation.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!obligation) return res.status(404).end(); res.json(envelope(obligation, req)); } catch (e) { next(e); } });
router.patch('/obligations/:id', requireAuth, requirePermission('obligation:update'), validate(obligationPatch), async (req, res, next) => { try { const obligation: any = await Obligation.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!obligation) return res.status(404).end(); if (obligation.version !== req.body.version) throw new Error('VERSION_CONFLICT'); Object.assign(obligation, req.body); if (req.body.dueDate) obligation.dueDate = new Date(req.body.dueDate); obligation.version += 1; await obligation.save(); res.json(envelope(obligation, req)); } catch (e) { next(e); } });
router.post('/obligations/:id/complete', requireAuth, requirePermission('obligation:complete'), validate(obligationComplete), async (req, res, next) => { try { const obligation: any = await Obligation.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req), ownerId: asId(req.auth!.userId) }); if (!obligation) throw new Error('OBLIGATION_NOT_FOUND'); if (obligation.version !== req.body.version) throw new Error('VERSION_CONFLICT'); obligation.status = 'completed'; obligation.completionData = { note: req.body.completionNote, completedBy: req.auth!.userId, completedAt: new Date() }; obligation.evidenceDocuments = req.body.evidenceDocuments ?? []; obligation.version += 1; await obligation.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'obligation.completed', entity: { type: 'obligation', id: obligation.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'ObligationCompleted.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: obligation.id, requestId: req.requestId, payload: { contractId: String(obligation.contractId), obligationId: obligation.id } }); res.json(envelope(obligation, req)); } catch (e) { next(e); } });
router.get('/documents', requireAuth, requirePermission('document:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.contractId && req.query.contractId !== 'all') filter.contractId = asId(String(req.query.contractId)); if (req.query.obligationId) filter.obligationId = asId(String(req.query.obligationId)); if (req.query.scanStatus) filter.scanStatus = String(req.query.scanStatus); const fingerprint = queryFingerprint({ tenant: tenant(req), filter, sort: 'createdAt:-1,_id:-1' }); const cursor = decodeCursor(req.query.cursor); if (cursor && cursor.fingerprint !== fingerprint) throw new Error('INVALID_CURSOR'); if (cursor) filter.$or = [{ createdAt: { $lt: new Date(cursor.updatedAt) } }, { createdAt: new Date(cursor.updatedAt), _id: { $lt: asId(cursor.id) } }]; const data = await Document.find(filter).select('-storageKey').sort({ createdAt: -1, _id: -1 }).limit(pageLimit(req.query.limit) + 1); res.json(paged(req, data, fingerprint)); } catch (e) { next(e); } });
router.post('/documents/upload', requireAuth, requirePermission('document:upload'), validate(documentUpload), async (req, res, next) => { try { const contract = await Contract.findOne({ _id: asId(req.body.contractId), tenantId: tenant(req) }); if (!contract) throw new Error('CONTRACT_NOT_FOUND'); if (req.body.obligationId && !(await Obligation.exists({ _id: asId(req.body.obligationId), contractId: contract._id, tenantId: tenant(req) }))) throw new Error('DOCUMENT_SCOPE_INVALID'); const documentId = new (await import('mongoose')).default.Types.ObjectId(); const key = storageKey(tenant(req), String(documentId)); const upload = await storageProvider.createUploadUrl({ key, mimeType: req.body.mimeType, sizeBytes: req.body.sizeBytes, checksum: req.body.checksum }); const doc = await Document.create({ _id: documentId, tenantId: tenant(req), contractId: contract._id, contractVersionId: req.body.versionId ? asId(req.body.versionId) : contract.currentVersionId, obligationId: req.body.obligationId ? asId(req.body.obligationId) : undefined, documentType: req.body.documentType, fileName: req.body.fileName, originalFileName: req.body.fileName, mimeType: req.body.mimeType, sizeBytes: req.body.sizeBytes, checksum: req.body.checksum, classification: req.body.classification, storageProvider: 'mock', storageKey: key, uploadStatus: 'pending', scanStatus: 'pending', uploadedBy: req.auth!.userId }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'document.upload_started', entity: { type: 'document', id: doc.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'DocumentUploadStarted.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: doc.id, requestId: req.requestId, payload: { documentId: doc.id, contractId: contract.id } }); res.status(201).json(envelope({ documentId: doc.id, uploadUrl: upload.url, uploadHeaders: upload.headers, expiresAt: upload.expiresAt, status: doc.uploadStatus }, req)); } catch (e) { next(e); } });
router.post('/documents/:id/index', requireAuth, requirePermission('document:index'), async (req, res, next) => { try { const result = await indexDocument(tenant(req), String(req.params.id), req.auth!.userId); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'document.indexed', entity: { type: 'document', id: String(req.params.id) }, metadata: result, requestId: req.requestId, result: 'success' }); res.status(202).json(envelope(result, req)); } catch (e) { next(e); } });
router.post('/search/semantic', requireAuth, requirePermission('contract:read'), validate(semanticSearch), async (req, res, next) => { try { const result = await runSemanticSearch(tenant(req), req.body.q, req.body.contractId, req.body.limit); res.json(envelope(result, req)); } catch (e) { next(e); } });
router.post('/documents/:id/finalize', requireAuth, requirePermission('document:upload'), validate(documentFinalize), async (req, res, next) => { try { const doc: any = await Document.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('+storageKey'); if (!doc) throw new Error('DOCUMENT_NOT_FOUND'); const verified = await storageProvider.verifyUpload(doc.storageKey); if (!verified.exists || verified.checksum !== req.body.checksum || req.body.checksum !== doc.checksum) throw new Error('DOCUMENT_CHECKSUM_MISMATCH'); const scan = await documentScanner.scan({ fileName: doc.fileName, mimeType: doc.mimeType, checksum: doc.checksum }); doc.uploadStatus = scan.status === 'infected' ? 'quarantined' : 'uploaded'; doc.scanStatus = scan.status; doc.scanMetadata = { signature: scan.signature, scannedAt: new Date() }; doc.version += 1; await doc.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'document.uploaded', entity: { type: 'document', id: doc.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'DocumentUploaded.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: doc.id, requestId: req.requestId, payload: { documentId: doc.id, contractId: String(doc.contractId), scanStatus: doc.scanStatus } }); await publishEvent({ name: 'DocumentScanCompleted.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: doc.id, requestId: req.requestId, payload: { documentId: doc.id, scanStatus: doc.scanStatus } }); res.json(envelope({ documentId: doc.id, uploadStatus: doc.uploadStatus, scanStatus: doc.scanStatus }, req)); } catch (e) { next(e); } });
router.get('/documents/:id', requireAuth, requirePermission('document:read'), async (req, res, next) => { try { const doc = await Document.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('-storageKey'); if (!doc) throw new Error('DOCUMENT_NOT_FOUND'); res.json(envelope(doc, req)); } catch (e) { next(e); } });
router.get('/documents/:id/download', requireAuth, requirePermission('document:download'), async (req, res, next) => { try { const doc: any = await Document.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('+storageKey'); if (!doc) throw new Error('DOCUMENT_NOT_FOUND'); if (doc.uploadStatus === 'deleted' || doc.uploadStatus === 'quarantined' || doc.scanStatus !== 'clean') throw new Error('DOCUMENT_NOT_AVAILABLE'); const download = await storageProvider.createDownloadUrl(doc.storageKey); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'document.downloaded', entity: { type: 'document', id: doc.id }, requestId: req.requestId, result: 'success' }); res.json(envelope({ url: download.url, expiresAt: download.expiresAt }, req)); } catch (e) { next(e); } });
router.delete('/documents/:id', requireAuth, requirePermission('document:delete'), validate(documentDelete), async (req, res, next) => { try { const doc: any = await Document.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('+storageKey'); if (!doc) throw new Error('DOCUMENT_NOT_FOUND'); if (doc.version !== req.body.version) throw new Error('VERSION_CONFLICT'); await storageProvider.deleteObject(doc.storageKey); doc.uploadStatus = 'deleted'; doc.version += 1; await doc.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'document.deleted', entity: { type: 'document', id: doc.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'DocumentDeleted.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: doc.id, requestId: req.requestId, payload: { documentId: doc.id, contractId: String(doc.contractId) } }); res.status(204).end(); } catch (e) { next(e); } });
router.get('/dashboard/summary', requireAuth, requirePermission('report:read'), async (req, res, next) => { try { const data = await getDashboardSummary(tenant(req)); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'dashboard.summary.read', entity: { type: 'dashboard', id: 'summary' }, requestId: req.requestId, result: 'success' }); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.get('/dashboard/contracts', requireAuth, requirePermission('report:read'), async (req, res, next) => { try { const data = await getContractAnalytics(tenant(req)); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'dashboard.contracts.read', entity: { type: 'dashboard', id: 'contracts' }, requestId: req.requestId, result: 'success' }); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.get('/dashboard/approvals', requireAuth, requirePermission('report:read'), async (req, res, next) => { try { const data = await getApprovalAnalytics(tenant(req)); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'dashboard.approvals.read', entity: { type: 'dashboard', id: 'approvals' }, requestId: req.requestId, result: 'success' }); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.get('/dashboard/obligations', requireAuth, requirePermission('report:read'), async (req, res, next) => { try { const data = await getObligationAnalytics(tenant(req)); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'dashboard.obligations.read', entity: { type: 'dashboard', id: 'obligations' }, requestId: req.requestId, result: 'success' }); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.get('/notifications', requireAuth, async (req, res, next) => { try { const filter: any = { tenantId: tenant(req), recipientUserId: asId(req.auth!.userId) }; if (req.query.status) filter.status = req.query.status; if (req.query.type) filter.type = req.query.type; const notifications = await Notification.find(filter).sort({ createdAt: -1, _id: -1 }).limit(pageLimit(req.query.limit) + 1); res.json(paged(req, notifications, queryFingerprint({ tenant: tenant(req), userId: req.auth!.userId, filter, sort: 'createdAt:-1,_id:-1' }))); } catch (e) { next(e); } });
router.patch('/notifications/:id/read', requireAuth, async (req, res, next) => { try { const result = z.object({ version: z.number().int().positive() }).strict().parse(req.body); const notification: any = await Notification.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req), recipientUserId: asId(req.auth!.userId) }); if (!notification) throw new Error('NOTIFICATION_NOT_FOUND'); if (notification.version !== result.version) throw new Error('VERSION_CONFLICT'); notification.status = 'read'; notification.readAt = new Date(); notification.version += 1; await notification.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'notification.read', entity: { type: 'notification', id: notification.id }, requestId: req.requestId, result: 'success' }); await publishEvent({ name: 'NotificationRead.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: notification.id, requestId: req.requestId, payload: { notificationId: notification.id } }); res.json(envelope(notification, req)); } catch (e) { next(e); } });
router.post('/notifications/preferences', requireAuth, validate(notificationPreferences), async (req, res, next) => { try { const preference = await NotificationPreference.findOneAndUpdate({ tenantId: tenant(req), userId: asId(req.auth!.userId) }, { $set: { ...req.body, tenantId: tenant(req), userId: asId(req.auth!.userId) } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await publishEvent({ name: 'NotificationPreferenceChanged.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: String(preference?._id), requestId: req.requestId, payload: { userId: req.auth!.userId } }); res.json(envelope(preference, req)); } catch (e) { next(e); } });
router.get('/notifications/preferences', requireAuth, async (req, res, next) => { try { const preference = await NotificationPreference.findOne({ tenantId: tenant(req), userId: asId(req.auth!.userId) }); res.json(envelope(preference, req)); } catch (e) { next(e); } });
router.get('/audit', requireAuth, requirePermission('audit:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.action) filter.action = req.query.action; if (req.query.actorId) filter.actorId = req.query.actorId; const events = await AuditLog.find(filter).sort({ timestamp: -1 }).limit(Math.min(Number(req.query.limit) || 50, 100)); res.json(envelope(events, req)); } catch (e) { next(e); } });

router.get('/templates', requireAuth, requirePermission('template:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.contractType) filter.contractType = req.query.contractType; if (req.query.status) filter.status = req.query.status; res.json(envelope(await Template.find(filter).sort({ updatedAt: -1 }).limit(100), req)); } catch (e) { next(e); } });
router.post('/templates', requireAuth, requirePermission('template:create'), validate(templateCreate), async (req, res, next) => { try { const template = await Template.create({ ...req.body, tenantId: tenant(req), ownerId: req.auth!.userId, status: 'draft' }); await TemplateVersion.create({ tenantId: tenant(req), templateId: template.id, versionNumber: 1, status: 'draft', clauseRefs: req.body.clauseRefs ?? [], variables: req.body.variables ?? [], authorId: req.auth!.userId }); res.status(201).json(envelope(template, req)); } catch (e) { next(e); } });
router.get('/templates/:id', requireAuth, requirePermission('template:read'), async (req, res, next) => { try { const t = await Template.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!t) return res.status(404).end(); res.json(envelope(t, req)); } catch (e) { next(e); } });
router.patch('/templates/:id', requireAuth, requirePermission('template:update'), async (req, res, next) => { try { const t = await Template.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!t) return res.status(404).end(); if (t.status === 'published' && req.body.status === 'published') throw new Error('CONFLICT'); Object.assign(t, req.body); await t.save(); if (req.body.status === 'published') await TemplateVersion.updateOne({ templateId: t.id, versionNumber: t.currentVersion }, { $set: { status: 'published', publishedAt: new Date() } }); res.json(envelope(t, req)); } catch (e) { next(e); } });

router.get('/clauses', requireAuth, requirePermission('clause:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; for (const field of ['category', 'riskClassification', 'status']) if (req.query[field]) filter[field] = req.query[field]; if (req.query.q) filter.$or = [{ title: new RegExp(String(req.query.q), 'i') }, { body: new RegExp(String(req.query.q), 'i') }]; res.json(envelope(await Clause.find(filter).sort({ updatedAt: -1 }).limit(100), req)); } catch (e) { next(e); } });
router.post('/clauses', requireAuth, requirePermission('clause:create'), validate(clauseCreate), async (req, res, next) => { try { const clause = await Clause.create({ ...req.body, tenantId: tenant(req), ownerId: req.auth!.userId, status: 'draft', versionNumber: 1 }); await ClauseVersion.create({ tenantId: tenant(req), clauseId: clause.id, versionNumber: 1, body: clause.body, status: 'draft', authorId: req.auth!.userId }); res.status(201).json(envelope(clause, req)); } catch (e) { next(e); } });
router.patch('/clauses/:id', requireAuth, requirePermission('clause:update'), async (req, res, next) => { try { const clause = await Clause.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!clause) return res.status(404).end(); if (clause.status === 'approved' && req.body.status === 'approved') throw new Error('CONFLICT'); Object.assign(clause, req.body); clause.versionNumber += 1; await clause.save(); await ClauseVersion.create({ tenantId: tenant(req), clauseId: clause.id, versionNumber: clause.versionNumber, body: clause.body, status: clause.status, authorId: req.auth!.userId, approvedBy: clause.status === 'approved' ? req.auth!.userId : undefined, publishedAt: clause.status === 'approved' ? new Date() : undefined }); res.json(envelope(clause, req)); } catch (e) { next(e); } });

router.get('/workflows', requireAuth, requirePermission('workflow:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.status) filter.status = req.query.status; if (req.query.contractType) filter.contractType = req.query.contractType; res.json(envelope(await Workflow.find(filter).sort({ updatedAt: -1 }).limit(100), req)); } catch (e) { next(e); } });
router.post('/workflows', requireAuth, requirePermission('workflow:create'), validate(workflowCreate), async (req, res, next) => { try { const workflow = await Workflow.create({ ...req.body, tenantId: tenant(req), ownerId: req.auth!.userId, status: 'draft' }); await WorkflowVersion.create({ tenantId: tenant(req), workflowId: workflow.id, versionNumber: 1, status: 'draft', triggerRules: req.body.triggerRules ?? [], stages: req.body.stages ?? [], rejectionPolicy: req.body.rejectionPolicy, authorId: req.auth!.userId }); res.status(201).json(envelope(workflow, req)); } catch (e) { next(e); } });
router.get('/workflows/:id', requireAuth, requirePermission('workflow:read'), async (req, res, next) => { try { const workflow = await Workflow.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!workflow) return res.status(404).end(); res.json(envelope(workflow, req)); } catch (e) { next(e); } });
router.patch('/workflows/:id', requireAuth, requirePermission('workflow:update'), async (req, res, next) => { try { const workflow = await Workflow.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }); if (!workflow) return res.status(404).end(); if (workflow.status === 'published') throw new Error('CONFLICT'); Object.assign(workflow, req.body); await workflow.save(); if (req.body.status === 'published') await WorkflowVersion.updateOne({ workflowId: workflow.id, versionNumber: workflow.currentVersion }, { $set: { status: 'published', publishedAt: new Date() } }); res.json(envelope(workflow, req)); } catch (e) { next(e); } });

router.get('/approvals', requireAuth, requirePermission('approval:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.status) filter.status = req.query.status; if (req.query.assignedUserId) filter.assignedUserId = asId(String(req.query.assignedUserId)); const data = await ApprovalTask.find(filter).sort({ createdAt: -1, _id: -1 }).limit(pageLimit(req.query.limit) + 1); res.json(paged(req, data, queryFingerprint({ tenant: tenant(req), filter, sort: 'createdAt:-1,_id:-1' }))); } catch (e) { next(e); } });
router.get('/contracts/:id/approvals', requireAuth, requirePermission('approval:read'), async (req, res, next) => { try { const tasks = await ApprovalTask.find({ tenantId: tenant(req), contractId: asId(String(req.params.id)) }).sort({ createdAt: 1 }); res.json(envelope(tasks, req)); } catch (e) { next(e); } });
router.post('/approvals/:id/approve', requireAuth, requirePermission('approval:approve'), validate(approvalAction), async (req, res, next) => { try { const task = await completeApproval(String(req.params.id), req.auth!.userId, 'approved', req.body.comment, req.requestId); res.json(envelope(task, req)); } catch (e) { next(e); } });
router.post('/approvals/:id/reject', requireAuth, requirePermission('approval:reject'), validate(approvalAction), async (req, res, next) => { try { if (!req.body.reason) return res.status(400).json({ success: false, error: { code: 'APPROVAL_REASON_REQUIRED', message: 'Rejection reason is required' } }); const task = await completeApproval(String(req.params.id), req.auth!.userId, 'rejected', req.body.reason, req.requestId); res.json(envelope(task, req)); } catch (e) { next(e); } });
router.post('/approvals/:id/delegate', requireAuth, requirePermission('approval:delegate'), validate(approvalAction), async (req, res, next) => { try { if (!req.body.delegateToUserId || !req.body.reason || !req.body.expiresAt || new Date(req.body.expiresAt) <= new Date()) return res.status(400).json({ success: false, error: { code: 'DELEGATION_INVALID', message: 'Delegate user, reason, and future expiration date are required' } }); const delegate = await User.findOne({ _id: asId(req.body.delegateToUserId), tenantId: tenant(req), status: 'active' }); if (!delegate) return res.status(400).json({ success: false, error: { code: 'DELEGATE_USER_NOT_FOUND', message: 'Delegate user is not active in this tenant' } }); const task: any = await ApprovalTask.findOneAndUpdate({ _id: asId(String(req.params.id)), tenantId: tenant(req), assignedUserId: asId(req.auth!.userId), status: { $in: ['pending', 'in_progress'] } }, { $set: { assignedUserId: delegate._id, status: 'delegated', comments: req.body.reason, delegation: { delegatedBy: req.auth!.userId, expiresAt: new Date(req.body.expiresAt) } }, $push: { history: { action: 'delegated', actorId: req.auth!.userId, delegateTo: delegate.id, reason: req.body.reason, expiresAt: new Date(req.body.expiresAt), at: new Date() } } }, { new: true }); if (!task) throw new Error('CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'approval.delegated', entity: { type: 'approvalTask', id: task.id }, metadata: { delegateTo: delegate.id, expiresAt: req.body.expiresAt }, result: 'success' }); res.json(envelope(task, req)); } catch (e) { next(e); } });


router.get('/intake/questionnaires', requireAuth, requirePermission('intake:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req), status: 'published' }; if (req.query.contractType) filter.contractType = String(req.query.contractType); const data = await IntakeQuestionnaire.find(filter).sort({ contractType: 1, version: -1 }).lean(); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/intake/questionnaires', requireAuth, requirePermission('intake:manage'), async (req, res, next) => { try { const body = z.object({ contractType: z.string().min(1).max(100), status: z.enum(['draft', 'published', 'retired']).default('draft'), questions: z.array(z.object({ key: z.string().regex(/^[a-z][a-z0-9_]*$/), label: z.string().min(1).max(200), type: z.enum(['text', 'textarea', 'number', 'date', 'select', 'boolean']), required: z.boolean().default(false), options: z.array(z.string().max(100)).max(50).optional(), visibleWhen: z.unknown().optional() }).strict()).max(100), routingRules: z.array(z.unknown()).max(100).default([]) }).strict().parse(req.body); const latest: any = await IntakeQuestionnaire.findOne({ tenantId: tenant(req), contractType: body.contractType }).sort({ version: -1 }); const questionnaire = await IntakeQuestionnaire.create({ tenantId: tenant(req), contractType: body.contractType, version: (latest?.version ?? 0) + 1, status: body.status, questions: body.questions, routingRules: body.routingRules, ownerId: req.auth!.userId }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'intake.questionnaire.created', entity: { type: 'intakeQuestionnaire', id: questionnaire.id }, metadata: { contractType: body.contractType, version: questionnaire.version }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope(questionnaire, req)); } catch (e) { next(e); } });
router.get('/intake/requests', requireAuth, requirePermission('intake:read'), async (req, res, next) => { try { const filter: any = { tenantId: tenant(req) }; if (req.query.status) filter.status = String(req.query.status); if (req.query.requesterId) filter.requesterId = asId(String(req.query.requesterId)); const data = await IntakeRequest.find(filter).sort({ createdAt: -1, _id: -1 }).limit(Math.min(Number(req.query.limit) || 50, 100)); res.json(envelope(data, req)); } catch (e) { next(e); } });
router.post('/intake/requests', requireAuth, requirePermission('intake:create'), async (req, res, next) => { try { const body = z.object({ title: z.string().min(1).max(240), contractType: z.string().min(1).max(100), questionnaireVersion: z.number().int().positive().optional(), answers: z.record(z.string(), z.unknown()).default({}), attachments: z.array(z.string()).max(20).default([]), priority: z.enum(['low', 'normal', 'high', 'urgent']).default('normal') }).strict().parse(req.body); const questionnaire: any = await IntakeQuestionnaire.findOne({ tenantId: tenant(req), contractType: body.contractType, status: 'published', ...(body.questionnaireVersion ? { version: body.questionnaireVersion } : {}) }).sort({ version: -1 }); if (!questionnaire) throw new Error('INTAKE_QUESTIONNAIRE_NOT_FOUND'); const missing = (questionnaire.questions ?? []).filter((q: any) => q.required && (body.answers[q.key] === undefined || body.answers[q.key] === null || body.answers[q.key] === '')).map((q: any) => q.key); if (missing.length) throw Object.assign(new Error('INTAKE_REQUIRED_ANSWERS_MISSING'), { details: { missing } }); const request = await IntakeRequest.create({ tenantId: tenant(req), requesterId: req.auth!.userId, title: body.title, contractType: body.contractType, questionnaireVersion: questionnaire.version, answers: body.answers, attachments: body.attachments.map(asId), priority: body.priority, status: 'submitted' }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'intake.request.submitted', entity: { type: 'intakeRequest', id: request.id }, metadata: { contractType: body.contractType, priority: body.priority }, result: 'success', requestId: req.requestId }); await publishEvent({ name: 'IntakeRequestSubmitted.v1', tenantId: tenant(req), actorId: req.auth!.userId, entityId: request.id, requestId: req.requestId, payload: { intakeRequestId: request.id, contractType: body.contractType } }); res.status(201).json(envelope(request, req)); } catch (e) { next(e); } });
router.post('/intake/requests/:id/convert', requireAuth, requirePermission('intake:manage'), async (req, res, next) => { try { const request: any = await IntakeRequest.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req), status: { $in: ['submitted', 'triage', 'in_progress'] } }); if (!request) throw new Error('INTAKE_REQUEST_NOT_FOUND'); const contract = await Contract.create({ tenantId: tenant(req), contractNumber: String(req.body.contractNumber ?? `INTAKE-${String(request._id).slice(-8).toUpperCase()}`), title: request.title, contractType: request.contractType, ownerId: request.requesterId, status: 'draft', metadata: { intakeRequestId: request.id, answers: request.answers } }); const version = await ContractVersion.create({ tenantId: tenant(req), contractId: contract.id, versionNumber: 1, state: 'draft', authorId: req.auth!.userId, changeSummary: 'Created from intake request' }); contract.currentVersionId = version.id; await contract.save(); request.status = 'converted'; request.version += 1; request.conversion = { contractId: contract.id, convertedBy: req.auth!.userId, convertedAt: new Date() }; await request.save(); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'intake.request.converted', entity: { type: 'intakeRequest', id: request.id }, metadata: { contractId: contract.id }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope({ request, contract }, req)); } catch (e) { next(e); } });

router.get('/integrations', requireAuth, requirePermission('integration:read'), async (req, res, next) => { try { const data = await Integration.find({ tenantId: tenant(req) }).sort({ updatedAt: -1 }).lean(); res.json(envelope(data.map(redactedIntegration), req)); } catch (e) { next(e); } });
router.post('/integrations', requireAuth, requirePermission('integration:create'), async (req, res, next) => { try { const body = z.object({ type: z.enum(supportedIntegrationTypes), provider: z.string().min(1).max(80), displayName: z.string().min(1).max(160), config: z.record(z.string(), z.unknown()).default({}), secret: z.unknown().optional() }).strict().parse(req.body); const encrypted = body.secret === undefined ? {} : encryptSecret(body.secret); const integration = await Integration.findOneAndUpdate({ tenantId: tenant(req), type: body.type, provider: body.provider }, { $set: { displayName: body.displayName, config: body.config, ...encrypted, status: 'draft', updatedAt: new Date() }, $setOnInsert: { tenantId: tenant(req), type: body.type, provider: body.provider, version: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'integration.created', entity: { type: 'integration', id: integration.id }, metadata: { provider: body.provider, type: body.type }, result: 'success', requestId: req.requestId }); res.status(201).json(envelope(redactedIntegration(integration), req)); } catch (e) { next(e); } });
router.patch('/integrations/:id', requireAuth, requirePermission('integration:update'), async (req, res, next) => { try { const body = z.object({ displayName: z.string().min(1).max(160).optional(), config: z.record(z.string(), z.unknown()).optional(), secret: z.unknown().optional(), status: z.enum(['draft', 'connected', 'degraded', 'disabled']).optional(), version: z.number().int().positive() }).strict().parse(req.body); const current: any = await Integration.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('+secretCiphertext +secretIv +secretTag'); if (!current || current.version !== body.version) throw new Error('VERSION_CONFLICT'); const update: any = { updatedAt: new Date(), version: current.version + 1 }; if (body.displayName !== undefined) update.displayName = body.displayName; if (body.config !== undefined) update.config = body.config; if (body.status !== undefined) update.status = body.status; if (body.secret !== undefined) Object.assign(update, encryptSecret(body.secret)); const integration = await Integration.findOneAndUpdate({ _id: current._id, tenantId: tenant(req), version: body.version }, { $set: update }, { new: true }); if (!integration) throw new Error('VERSION_CONFLICT'); await writeAudit({ tenantId: tenant(req), actorId: req.auth!.userId, action: 'integration.updated', entity: { type: 'integration', id: integration.id }, metadata: { status: integration.status }, result: 'success', requestId: req.requestId }); res.json(envelope(redactedIntegration(integration), req)); } catch (e) { next(e); } });
router.post('/integrations/:id/test', requireAuth, requirePermission('integration:update'), async (req, res, next) => { try { const integration: any = await Integration.findOne({ _id: asId(String(req.params.id)), tenantId: tenant(req) }).select('+secretCiphertext +secretIv +secretTag'); if (!integration) throw new Error('RESOURCE_NOT_FOUND'); const secret = integration.secretCiphertext ? decryptSecret(integration) : undefined; const health = providerHealthStatus(integration.type, secret); integration.status = health.status; integration.lastHealthCheckAt = new Date(); integration.lastError = health.status === 'connected' ? undefined : health.message; await integration.save(); res.json(envelope({ ...redactedIntegration(integration), health }, req)); } catch (e) { next(e); } });

router.post('/webhooks/:provider', async (req, res, next) => { try { const provider = String(req.params.provider); if (!supportedIntegrationTypes.includes(provider as any)) throw new Error('UNSUPPORTED_PROVIDER'); const externalEventId = String(req.header('x-event-id') ?? req.body?.event_id ?? req.body?.eventId ?? ''); if (!externalEventId) throw new Error('WEBHOOK_EVENT_ID_REQUIRED'); const rawBody = JSON.stringify(req.body ?? {}); const payloadHash = crypto.createHash('sha256').update(rawBody).digest('hex'); const integration: any = await Integration.findOne({ type: provider, status: { $in: ['connected', 'degraded'] } }).select('+secretCiphertext +secretIv +secretTag').sort({ updatedAt: -1 }); const secret = integration?.secretCiphertext ? decryptSecret(integration) : undefined; const signature = req.header('x-signature') ?? req.header('x-slack-signature') ?? undefined; const timestamp = req.header('x-slack-request-timestamp') ?? undefined; const valid = provider === 'slack' ? Boolean(secret?.signingSecret && verifySlackSignature(rawBody, signature, timestamp, secret.signingSecret)) : Boolean(secret?.webhookSecret && verifyHmacSignature(rawBody, signature, secret.webhookSecret)); if (!valid) return res.status(401).json({ success: false, error: { code: 'WEBHOOK_SIGNATURE_INVALID', message: 'Webhook signature verification failed' } }); const existing = await WebhookEvent.findOne({ tenantId: integration.tenantId, provider, externalEventId }); if (existing) return res.status(200).json({ success: true, data: { received: true, duplicate: true } }); const record = await WebhookEvent.create({ tenantId: integration.tenantId, provider, externalEventId, eventType: String(req.body?.type ?? req.body?.event?.type ?? 'unknown'), signatureValid: true, payloadHash, status: 'received' }); await publishEvent({ name: 'IntegrationWebhookReceived.v1', tenantId: String(integration.tenantId), entityId: record.id, payload: { provider, webhookEventId: record.id, externalEventId } }); res.status(202).json({ success: true, data: { received: true, webhookEventId: record.id } }); } catch (e) { next(e); } });

export default router;
