import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, CheckCircle2, FileSearch, MessageSquareText, ShieldAlert, Sparkles } from 'lucide-react';
import { endpoints, listItems } from '../services/api';
import { parseForm, intelligenceQuestionSchema, type ContractIntelligence, type IntelligenceRisk, type IntelligenceTerm } from '../services/types';

function tone(severity?: string) { return severity === 'critical' || severity === 'high' ? 'badge-red' : severity === 'medium' ? 'badge-orange' : 'badge-green'; }
function pct(value?: number) { return `${Math.round((value ?? 0) * 100)}%`; }

export function Intelligence() {
  const [contractId, setContractId] = useState('');
  const [items, setItems] = useState<ContractIntelligence[]>([]);
  const [question, setQuestion] = useState('');
  const [playbook, setPlaybook] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');

  const analyses = useMemo(() => items.filter((item) => item.kind === 'analysis'), [items]);
  const questions = useMemo(() => items.filter((item) => item.kind === 'question'), [items]);
  const latest = analyses[0];
  const load = async () => { if (!contractId.trim()) return; setBusy(true); setMessage(''); try { setItems(listItems(await endpoints.contractIntelligence(contractId.trim()))); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load intelligence'); } finally { setBusy(false); } };
  useEffect(() => { if (contractId.trim()) void load(); }, []);

  const analyze = async () => { if (!contractId.trim()) { setMessage('Enter a contract ID first.'); return; } setBusy(true); setMessage('CovenX Intelligence is reviewing the authorized contract evidence…'); try { const result = await endpoints.analyzeContract(contractId.trim(), { playbook: playbook.split('\n').map((line) => line.trim()).filter(Boolean) }); setItems((current) => [result, ...current.filter((item) => item._id !== result._id)]); setMessage('Analysis generated. Review every finding before taking action.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Analysis failed'); } finally { setBusy(false); } };
  const ask = async () => { if (!contractId.trim()) { setMessage('Enter a contract ID first.'); return; } try { const body = parseForm(intelligenceQuestionSchema, { question, intelligenceId: latest?._id }); setBusy(true); setMessage('Searching only the authorized contract evidence…'); const result = await endpoints.askContract(contractId.trim(), body); setItems((current) => [result, ...current]); setQuestion(''); setMessage('Answer generated with evidence citations.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Question could not be answered'); } finally { setBusy(false); } };
  const review = async (item: ContractIntelligence, decision: 'accepted' | 'overridden') => { setBusy(true); try { const result = await endpoints.reviewIntelligence(item._id, { decision }); setItems((current) => current.map((entry) => entry._id === result._id ? result : entry)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Review could not be saved'); } finally { setBusy(false); } };

  return <>
    <div className="page-heading"><div><div className="eyebrow"><Sparkles size={12} /> CovenX Intelligence</div><h1>Contract intelligence workspace</h1><p className="subtitle">Generate explainable summaries, extract terms, surface risks, and ask evidence-grounded questions.</p></div><div className="badge badge-green"><BrainCircuit size={13} /> Human-reviewed by design</div></div>
    <div className="card panel intelligence-hero"><div className="panel-header"><div><h2>Start an authorized review</h2><p className="panel-caption">AI receives only the tenant-scoped contract record and selected version metadata.</p></div><FileSearch size={22} color="#1d9365" /></div><div className="form-grid"><div className="field full"><label htmlFor="intelligence-contract">Contract ID</label><input id="intelligence-contract" value={contractId} onChange={(event) => setContractId(event.target.value)} placeholder="Paste a CovenX contract ID" /></div><div className="field full"><label htmlFor="intelligence-playbook">Review playbook (one expectation per line)</label><textarea id="intelligence-playbook" value={playbook} onChange={(event) => setPlaybook(event.target.value)} placeholder="Example: Liability cap should not exceed twelve months of fees" /></div></div><div className="panel-actions"><button className="btn btn-primary" onClick={analyze} disabled={busy}><BrainCircuit size={15} /> {busy ? 'Reviewing…' : 'Analyze contract'}</button><button className="btn btn-secondary" onClick={load} disabled={busy}>Load previous reviews</button></div>{message && <div className="notice" role="status">{message}</div>}</div>
    {latest && <div className="grid-2 intelligence-grid"><section className="card panel"><div className="panel-header"><div><h2>Executive summary</h2><p className="panel-caption">{latest.provider} · {latest.model} · confidence {pct(latest.confidence)}</p></div><span className={`badge ${latest.status === 'accepted' ? 'badge-green' : 'badge-orange'}`}>{latest.status}</span></div><p className="intelligence-summary">{latest.summary}</p><div className="intelligence-review"><span>Human review decision</span><div><button className="btn btn-secondary" onClick={() => review(latest, 'accepted')} disabled={busy}><CheckCircle2 size={14} /> Accept</button><button className="btn btn-secondary" onClick={() => review(latest, 'overridden')} disabled={busy}>Override</button></div></div></section><section className="card panel"><div className="panel-header"><div><h2>Ask the contract</h2><p className="panel-caption">Answers cite the evidence used.</p></div><MessageSquareText size={21} color="#e87b28" /></div><textarea className="intelligence-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What are the renewal and termination requirements?" /><button className="btn btn-primary" onClick={ask} disabled={busy || question.trim().length < 3}><MessageSquareText size={14} /> Ask question</button></section></div>}
    {latest && <div className="grid-2 intelligence-grid"><section className="card panel"><div className="panel-header"><div><h2>Extracted terms</h2><p className="panel-caption">Each term includes confidence and evidence.</p></div></div><div className="intelligence-list">{(latest.keyTerms ?? []).map((term: IntelligenceTerm) => <div className="intelligence-item" key={`${term.name}-${term.evidence}`}><div><strong>{term.name}</strong><p>{term.value}</p><small>Evidence: {term.evidence}</small></div><span className="badge badge-blue">{pct(term.confidence)}</span></div>)}{!(latest.keyTerms ?? []).length && <div className="empty">No terms were extracted from the available evidence.</div>}</div></section><section className="card panel"><div className="panel-header"><div><h2>Risk findings</h2><p className="panel-caption">Explainable findings require human confirmation.</p></div><ShieldAlert size={21} color="#e87b28" /></div><div className="intelligence-list">{(latest.risks ?? []).map((risk: IntelligenceRisk) => <div className="intelligence-risk" key={`${risk.title}-${risk.evidence}`}><div className="panel-header"><strong>{risk.title}</strong><span className={`badge ${tone(risk.severity)}`}>{risk.severity}</span></div><p>{risk.explanation}</p><small>Recommendation: {risk.recommendation}</small><small>Evidence: {risk.evidence} · confidence {pct(risk.confidence)}</small></div>)}{!(latest.risks ?? []).length && <div className="empty">No risks were identified from the available evidence.</div>}</div></section></div>}
    {latest?.missingInformation?.length ? <div className="card panel"><h2>Missing information</h2><div className="notice">The assistant could not verify the following items: {latest.missingInformation.join(' · ')}</div></div> : null}
    {questions.length > 0 && <div className="card panel"><div className="panel-header"><div><h2>Question history</h2><p className="panel-caption">Evidence-grounded answers are retained in the contract intelligence audit trail.</p></div></div>{questions.map((item) => <div className="intelligence-item" key={item._id}><div><strong>{item.question}</strong><p>{item.answer}</p>{(item.citations ?? []).map((citation) => <small key={citation.label}>Citation — {citation.label}: {citation.evidence}</small>)}</div><span className={`badge ${item.needsHumanReview ? 'badge-orange' : 'badge-green'}`}>{item.needsHumanReview ? 'review' : 'ready'}</span></div>)}</div>}
    {analyses.length === 0 && !latest && <div className="card empty">Enter a contract ID to begin a governed CovenX Intelligence review.</div>}
  </>;
}
