import { FormEvent, useEffect, useState } from 'react';
import { Activity, CheckCircle2, ExternalLink, KeyRound, LogOut, Save, ShieldCheck, UserRound } from 'lucide-react';
import { endpoints, listItems } from '../services/api';
import { useAuth } from '../main';

export function Settings() {
  const { user } = useAuth();
  const [sessions, setSessions] = useState<any[]>([]);
  const [form, setForm] = useState({ displayName: user?.profile?.displayName ?? '', firstName: user?.profile?.firstName ?? '', lastName: user?.profile?.lastName ?? '' });
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { endpoints.sessions().then((d) => setSessions(listItems(d as any))).catch((e) => setError(e.message)); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!user?._id) return; try { await endpoints.updateUser(user._id, { profile: { displayName: form.displayName, firstName: form.firstName, lastName: form.lastName } }); setNotice('Profile saved successfully.'); } catch (e: any) { setError(e.message); } };
  const revoke = async (sessionId: string) => { try { await endpoints.revokeSession(sessionId); setSessions((current) => current.filter((session) => session.sessionId !== sessionId)); setNotice('Session revoked.'); } catch (e: any) { setError(e.message); } };
  const roles = (user?.roles ?? user?.roleIds ?? []).map((role: any) => typeof role === 'string' ? role : role.name ?? role.key).filter(Boolean);
  return <>
    <div className="page-heading"><div><div className="eyebrow">Workspace administration</div><h1>Security & access</h1><p className="subtitle">Manage identity, active sessions, tenant context, and governed access posture.</p></div><span className="badge badge-green"><ShieldCheck size={12} /> Protected workspace</span></div>
    {notice && <div className="notice settings-notice"><CheckCircle2 size={15} /> {notice}</div>}{error && <div className="notice settings-notice">{error}</div>}
    <div className="security-overview"><div className="security-score"><div className="security-score-ring"><ShieldCheck size={23} /></div><div><span>Access posture</span><strong>Governed</strong><small>Tenant-scoped controls active</small></div></div><div className="security-fact"><KeyRound size={17} /><div><strong>Short-lived sessions</strong><span>Rotating refresh credentials</span></div></div><div className="security-fact"><Activity size={17} /><div><strong>{sessions.length} active session{sessions.length === 1 ? '' : 's'}</strong><span>Review unfamiliar access</span></div></div></div>
    <div className="two-column"><section className="card panel"><div className="panel-header"><div><h2>Profile</h2><div className="panel-caption">Identity and access context</div></div><UserRound size={19} color="#1d9365" /></div><form className="form-grid" onSubmit={save}><div className="field"><label htmlFor="displayName">Display name</label><input id="displayName" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></div><div className="field"><label>Email</label><input readOnly value={user?.email ?? ''} /></div><div className="field"><label htmlFor="firstName">First name</label><input id="firstName" value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} /></div><div className="field"><label htmlFor="lastName">Last name</label><input id="lastName" value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} /></div><div className="field full" style={{ display: 'flex', justifyContent: 'flex-end', flexDirection: 'row' }}><button className="btn btn-primary" type="submit"><Save size={15} /> Save profile</button></div></form><div className="notice settings-inline-notice"><ShieldCheck size={15} /> Access is enforced by the CovenX API through tenant-scoped permissions.</div><div className="role-context"><span>Effective roles</span><div>{roles.length ? roles.map((role: string) => <span className="badge badge-blue" key={role}>{role}</span>) : <span className="panel-caption">Role context is managed by your administrator.</span>}</div></div></section><section className="card panel"><div className="panel-header"><div><h2>Active sessions</h2><div className="panel-caption">Revoke access you no longer recognize</div></div><LogOut size={19} color="#e68a36" /></div>{sessions.length === 0 ? <div className="empty" style={{ padding: 24 }}>No session records available.</div> : <div className="session-list">{sessions.map((session: any) => <div className="session-row" key={session.sessionId}><div><strong>{session.userAgent ?? 'CovenX session'}</strong><div className="panel-caption">{session.ip ?? 'Unknown IP'} · {session.createdAt ? new Date(session.createdAt).toLocaleDateString() : 'Active'}</div></div><button className="btn btn-secondary btn-compact" onClick={() => void revoke(session.sessionId)}>Revoke</button></div>)}</div>}</section></div>
    <div className="settings-shortcuts"><div><strong>Continue your governance work</strong><span>Review the activity trail or rotate provider credentials from the appropriate workspace.</span></div><div><button className="btn btn-secondary" onClick={() => { window.history.pushState({}, '', '/audit'); window.dispatchEvent(new PopStateEvent('popstate')); }}>Open audit log <ExternalLink size={14} /></button><button className="btn btn-secondary" onClick={() => { window.history.pushState({}, '', '/integrations'); window.dispatchEvent(new PopStateEvent('popstate')); }}>Manage integrations <ExternalLink size={14} /></button></div></div>
  </>;
}
