import { z } from 'zod';

const oid = z.string().regex(/^[a-f\d]{24}$/i, 'Invalid identifier');
const request = <T extends z.ZodType>(body: T) => z.object({ body, params: z.record(z.string(), z.string()).optional(), query: z.record(z.string(), z.string()).optional() });

export const contractCreate = request(z.object({ contractNumber: z.string().trim().min(1).max(80).optional(), title: z.string().trim().min(1).max(200), contractType: z.string().trim().min(1).max(80), parties: z.array(z.record(z.string(), z.unknown())).max(50), ownerId: oid.optional(), departmentId: oid.optional(), businessUnitId: oid.optional(), effectiveDate: z.string().datetime().optional(), expiryDate: z.string().datetime().optional(), financial: z.object({ value: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().length(3) }).optional(), metadata: z.record(z.string(), z.unknown()).optional() }).strict());
export const workflowCreate = request(z.object({ name: z.string().min(1).max(120), key: z.string().regex(/^[a-z0-9-]+$/), contractType: z.string().optional(), triggerRules: z.array(z.record(z.string(), z.unknown())).max(20), stages: z.array(z.object({ stageKey: z.string(), assignedUserId: oid.optional(), assignedRoleId: oid.optional(), slaHours: z.number().int().positive().max(8760).optional(), quorum: z.number().int().positive().max(100).optional(), escalation: z.record(z.string(), z.unknown()).optional() }).strict()).min(1).max(30), rejectionPolicy: z.record(z.string(), z.unknown()).optional() }).strict());
export const templateCreate = request(z.object({ name: z.string().min(1).max(120), key: z.string().regex(/^[a-z0-9-]+$/), contractType: z.string().min(1), description: z.string().max(2000).optional(), clauseRefs: z.array(oid).max(200).optional(), variables: z.array(z.record(z.string(), z.unknown())).max(100).optional() }).strict());
export const clauseCreate = request(z.object({ key: z.string().regex(/^[a-z0-9-]+$/), title: z.string().min(1).max(200), body: z.string().min(1).max(50000), category: z.string().max(80), riskClassification: z.enum(['low', 'medium', 'high', 'critical']), tags: z.array(z.string().max(50)).max(30).optional() }).strict());
export const approvalAction = request(z.object({ version: z.number().int().positive().optional(), comment: z.string().max(4000).optional(), reason: z.string().max(4000).optional(), delegateToUserId: oid.optional(), expiresAt: z.string().datetime().optional() }).strict());
