import { z } from 'zod';

const oid = z.string().regex(/^[a-f\d]{24}$/i, 'Invalid identifier');
export const request = <T extends z.ZodType>(body: T) => z.object({ body, params: z.record(z.string(), z.string()).optional(), query: z.record(z.string(), z.string()).optional() });

export const contractCreate = request(z.object({ contractNumber: z.string().trim().min(1).max(80).optional(), title: z.string().trim().min(1).max(200), contractType: z.string().trim().min(1).max(80), parties: z.array(z.record(z.string(), z.unknown())).max(50), ownerId: oid.optional(), departmentId: oid.optional(), businessUnitId: oid.optional(), effectiveDate: z.string().datetime().optional(), expiryDate: z.string().datetime().optional(), financial: z.object({ value: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().length(3) }).optional(), metadata: z.record(z.string(), z.unknown()).optional() }).strict());
export const workflowCreate = request(z.object({ name: z.string().min(1).max(120), key: z.string().regex(/^[a-z0-9-]+$/), contractType: z.string().optional(), triggerRules: z.array(z.record(z.string(), z.unknown())).max(20), stages: z.array(z.object({ stageKey: z.string(), assignedUserId: oid.optional(), assignedRoleId: oid.optional(), slaHours: z.number().int().positive().max(8760).optional(), quorum: z.number().int().positive().max(100).optional(), escalation: z.record(z.string(), z.unknown()).optional() }).strict()).min(1).max(30), rejectionPolicy: z.record(z.string(), z.unknown()).optional() }).strict());
export const templateCreate = request(z.object({ name: z.string().min(1).max(120), key: z.string().regex(/^[a-z0-9-]+$/), contractType: z.string().min(1), description: z.string().max(2000).optional(), clauseRefs: z.array(oid).max(200).optional(), variables: z.array(z.record(z.string(), z.unknown())).max(100).optional() }).strict());
export const clauseCreate = request(z.object({ key: z.string().regex(/^[a-z0-9-]+$/), title: z.string().min(1).max(200), body: z.string().min(1).max(50000), category: z.string().max(80), riskClassification: z.enum(['low', 'medium', 'high', 'critical']), tags: z.array(z.string().max(50)).max(30).optional() }).strict());
export const approvalAction = request(z.object({ version: z.number().int().positive().optional(), comment: z.string().max(4000).optional(), reason: z.string().max(4000).optional(), delegateToUserId: oid.optional(), expiresAt: z.string().datetime().optional() }).strict());
export const signatureRequest = request(z.object({ provider: z.string().min(1).max(80), contractVersionId: oid, expiresAt: z.string().datetime(), signers: z.array(z.object({ userId: oid.optional(), vendorIdentity: z.record(z.string(), z.unknown()).optional(), signingOrder: z.number().int().positive().optional() }).strict()).min(1).max(20) }).strict());
export const signatureEvidence = request(z.object({ evidenceRefs: z.array(z.record(z.string(), z.unknown())).max(20).default([]) }).strict());
export const obligationCreate = request(z.object({ contractId: oid, ownerId: oid, type: z.string().min(1).max(80), title: z.string().min(1).max(200), description: z.string().max(4000).optional(), priority: z.enum(['low', 'medium', 'high', 'critical']).optional(), dueDate: z.string().datetime(), recurrence: z.record(z.string(), z.unknown()).optional(), escalationPolicy: z.record(z.string(), z.unknown()).optional(), evidenceDocuments: z.array(z.record(z.string(), z.unknown())).max(20).optional() }).strict());
export const obligationPatch = request(z.object({ title: z.string().min(1).max(200).optional(), description: z.string().max(4000).optional(), priority: z.enum(['low', 'medium', 'high', 'critical']).optional(), dueDate: z.string().datetime().optional(), status: z.enum(['open', 'in_progress', 'overdue', 'cancelled']).optional(), escalationPolicy: z.record(z.string(), z.unknown()).optional(), evidenceDocuments: z.array(z.record(z.string(), z.unknown())).max(20).optional(), version: z.number().int().positive() }).strict());
export const obligationComplete = request(z.object({ completionNote: z.string().min(1).max(4000), evidenceDocuments: z.array(z.record(z.string(), z.unknown())).max(20).optional(), version: z.number().int().positive() }).strict());
export const renewalRequest = request(z.object({ targetExpiryDate: z.string().datetime().optional() }).strict());
export const documentUpload = request(z.object({ contractId: oid, versionId: oid.optional(), obligationId: oid.optional(), documentType: z.string().min(1).max(80), fileName: z.string().regex(/^[^\\/\\\\]{1,255}$/), mimeType: z.enum(['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain']), sizeBytes: z.number().int().positive().max(50 * 1024 * 1024), checksum: z.string().regex(/^[a-f0-9]{64}$/i), classification: z.enum(['public', 'internal', 'confidential', 'restricted']) }).strict());
export const documentFinalize = request(z.object({ checksum: z.string().regex(/^[a-f0-9]{64}$/i) }).strict());
export const documentDelete = request(z.object({ version: z.number().int().positive() }).strict());
