import { Request, Response, NextFunction } from 'express';
import { z, ZodType } from 'zod';
import { verifyAccess, AuthContext } from '../services/auth.js';
import { redis } from '../config/connections.js';

declare global { namespace Express { interface Request { auth?: AuthContext; requestId?: string } } }
const rateBuckets = new Map<string, { count: number; resetAt: number }>();
export function rateLimit(windowMs = 60_000, max = 120) { return (req: Request, res: Response, next: NextFunction) => { const key = `${req.ip}:${req.path}`; const now = Date.now(); const bucket = rateBuckets.get(key); if (!bucket || bucket.resetAt <= now) rateBuckets.set(key, { count: 1, resetAt: now + windowMs }); else if (++bucket.count > max) return res.status(429).json({ success: false, error: { code: 'RATE_LIMITED', message: 'Too many requests' }, meta: { requestId: req.requestId } }); next(); }; }

export function distributedRateLimit(scope: string, windowMs = 60_000, max = 120) { return async (req: Request, res: Response, next: NextFunction) => { const key = `ratelimit:${scope}:${req.auth?.userId ?? req.ip}`; try { if ((redis as any).status === 'ready') { const count = await redis.incr(key); if (count === 1) await redis.pexpire(key, windowMs); if (count > max) return res.status(429).json({ success: false, error: { code: 'RATE_LIMITED', message: 'Too many requests' }, meta: { requestId: req.requestId } }); } next(); } catch { next(); } }; }
export function requireAuth(req: Request, res: Response, next: NextFunction) {
  try { const token = req.headers.authorization?.replace(/^Bearer\s+/i, ''); if (!token) throw new Error(); req.auth = verifyAccess(token); next(); }
  catch { res.status(401).json({ success: false, error: { code: 'AUTHENTICATION_REQUIRED', message: 'Authentication is required' }, meta: { requestId: req.requestId } }); }
}
export function requirePermission(permission: string) { return (req: Request, res: Response, next: NextFunction) => { if (!req.auth?.permissions.includes(permission) && !req.auth?.permissions.includes('*')) return res.status(403).json({ success: false, error: { code: 'PERMISSION_DENIED', message: 'Permission denied' }, meta: { requestId: req.requestId } }); next(); }; }
export function validate(schema: ZodType) { return (req: Request, res: Response, next: NextFunction) => { const result = schema.safeParse({ body: req.body, params: req.params, query: req.query }); if (!result.success) return res.status(400).json({ success: false, error: { code: 'VALIDATION_FAILED', message: 'Request validation failed', details: result.error.issues }, meta: { requestId: req.requestId } }); req.body = (result.data as any).body; next(); }; }
export function notFound(_req: Request, res: Response) { res.status(404).json({ success: false, error: { code: 'RESOURCE_NOT_FOUND', message: 'Resource not found' } }); }
export function errorHandler(error: any, req: Request, res: Response, _next: NextFunction) { const known = ['INVALID_CREDENTIALS', 'TOKEN_INVALID', 'REFRESH_REUSE_DETECTED', 'CONFLICT', 'VERSION_CONFLICT', 'INVALID_CURSOR', 'WORKFLOW_NOT_SATISFIED', 'WORKFLOW_ASSIGNMENT_INVALID', 'INVALID_LIFECYCLE_TRANSITION', 'APPROVAL_NOT_ASSIGNED', 'CONTRACT_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'DOCUMENT_CHECKSUM_MISMATCH', 'DOCUMENT_NOT_AVAILABLE', 'SIGNATURE_CONTRACT_NOT_READY', 'SIGNER_NOT_AUTHORIZED', 'SIGNATURE_NOT_FOUND', 'SIGNERS_REQUIRED', 'OBLIGATION_SCOPE_INVALID', 'OBLIGATION_NOT_FOUND']; const code = known.includes(error?.message) ? error.message : 'INTERNAL_ERROR'; const status = code === 'INTERNAL_ERROR' ? 500 : code.includes('TOKEN') || code.includes('CREDENTIAL') ? 401 : code.includes('NOT_FOUND') ? 404 : code === 'INVALID_CURSOR' || code === 'INVALID_LIFECYCLE_TRANSITION' || code === 'CONFLICT' || code === 'VERSION_CONFLICT' ? 409 : 400; res.status(status).json({ success: false, error: { code, message: code === 'INTERNAL_ERROR' ? 'Unexpected server error' : code }, meta: { requestId: req.requestId } }); }
